### ISSUE TITLE
Race condition when making directories when running parallel

### ISSUE THREAD

**Issue by wtriplett** [poldracklab/mriqc#111]
From: `mriqc/mriqc/utils/mriqc_run.py`

```{python}
 87     if not op.exists(settings['output_dir']):
 88         os.makedirs(settings['output_dir'])
 89
 90     settings['work_dir'] = op.abspath(opts.work_dir)
 91     if not op.exists(settings['work_dir']):
 92         os.makedirs(settings['work_dir'])
```

I think multiple `mriqc` processes are being run using the `-S sub1 sub2 ...`, the check for existence of the dirs can't be reliable.

Example (under parametric launcher):
```
mriqc -i ds000171 -d anat -S sub-control01 -o ds151_mriqc.out -w ds151_mriqc.wrk
mriqc -i ds000171 -d anat -S sub-control02 -o ds151_mriqc.out -w ds151_mriqc.wrk
mriqc -i ds000171 -d anat -S sub-control03 -o ds151_mriqc.out -w ds151_mriqc.wrk
mriqc -i ds000171 -d anat -S sub-control04 -o ds151_mriqc.out -w ds151_mriqc.wrk
mriqc -i ds000171 -d anat -S sub-control05 -o ds151_mriqc.out -w ds151_mriqc.wrk
```
These all start about the same time and try to perform the same initialization of output/work/log directories.

**Comment by wtriplett** [comment]
Maybe this will help also.

```
WARNING: LAUNCHER_WORKDIR variable not set. Using current directory.
Launcher: Setup complete.

------------- SUMMARY ---------------
   Number of hosts:    10
   Working directory:  ds000171
   Processes per host: 4
   Total processes:    40
   Total jobs:         39
   Scheduling method:  dynamic

-------------------------------------
Launcher: Starting parallel tasks...
Warning: Permanently added '[nid00311]:6999,[10.128.1.58]:6999' (RSA) to the list of known hosts.
Warning: Permanently added '[nid00306]:6999,[10.128.1.53]:6999' (RSA) to the list of known hosts.
Warning: Permanently added '[nid00310]:6999,[10.128.1.57]:6999' (RSA) to the list of known hosts.
Warning: Permanently added '[nid00312]:6999,[10.128.1.59]:6999' (RSA) to the list of known hosts.
Warning: Permanently added '[nid00308]:6999,[10.128.1.55]:6999' (RSA) to the list of known hosts.
Warning: Permanently added '[nid00307]:6999,[10.128.1.54]:6999' (RSA) to the list of known hosts.
Warning: Permanently added '[nid00315]:6999,[10.128.1.62]:6999' (RSA) to the list of known hosts.
Warning: Permanently added '[nid00313]:6999,[10.128.1.60]:6999' (RSA) to the list of known hosts.
Warning: Permanently added '[nid00309]:6999,[10.128.1.56]:6999' (RSA) to the list of known hosts.
Warning: Permanently added '[nid00314]:6999,[10.128.1.61]:6999' (RSA) to the list of known hosts.
Reading: ~/.bashrc
Reading: ~/.bashrc
Reading: ~/.bashrc
Reading: ~/.bashrc
Reading: ~/.bashrc
Reading: ~/.bashrc
Reading: ~/.bashrc
Reading: ~/.bashrc
Reading: ~/.bashrc
Reading: ~/.bashrc
Launcher: Task 1 running job 2 on nid00306 (mriqc -i ds000171 -d anat -S sub-control02 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 0 running job 4 on nid00306 (mriqc -i ds000171 -d anat -S sub-control04 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 3 running job 1 on nid00306 (mriqc -i ds000171 -d anat -S sub-control01 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 2 running job 3 on nid00306 (mriqc -i ds000171 -d anat -S sub-control03 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 25 running job 6 on nid00312 (mriqc -i ds000171 -d anat -S sub-control06 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 27 running job 8 on nid00312 (mriqc -i ds000171 -d anat -S sub-control08 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 26 running job 5 on nid00312 (mriqc -i ds000171 -d anat -S sub-control05 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 24 running job 7 on nid00312 (mriqc -i ds000171 -d anat -S sub-control07 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 18 running job 10 on nid00310 (mriqc -i ds000171 -d anat -S sub-control10 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 19 running job 9 on nid00310 (mriqc -i ds000171 -d anat -S sub-control09 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 16 running job 11 on nid00310 (mriqc -i ds000171 -d anat -S sub-control11 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 17 running job 12 on nid00310 (mriqc -i ds000171 -d anat -S sub-control12 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 30 running job 15 on nid00313 (mriqc -i ds000171 -d anat -S sub-control15 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 29 running job 13 on nid00313 (mriqc -i ds000171 -d anat -S sub-control13 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 28 running job 14 on nid00313 (mriqc -i ds000171 -d anat -S sub-control14 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 31 running job 16 on nid00313 (mriqc -i ds000171 -d anat -S sub-control16 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 35 running job 18 on nid00314 (mriqc -i ds000171 -d anat -S sub-control18 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 34 running job 17 on nid00314 (mriqc -i ds000171 -d anat -S sub-control17 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 33 running job 19 on nid00314 (mriqc -i ds000171 -d anat -S sub-control19 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 32 running job 20 on nid00314 (mriqc -i ds000171 -d anat -S sub-control20 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 11 running job 22 on nid00308 (mriqc -i ds000171 -d anat -S sub-mdd02 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 10 running job 24 on nid00308 (mriqc -i ds000171 -d anat -S sub-mdd04 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 9 running job 21 on nid00308 (mriqc -i ds000171 -d anat -S sub-mdd01 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 8 running job 23 on nid00308 (mriqc -i ds000171 -d anat -S sub-mdd03 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 38 running job 25 on nid00315 (mriqc -i ds000171 -d anat -S sub-mdd05 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 37 running job 28 on nid00315 (mriqc -i ds000171 -d anat -S sub-mdd08 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 36 running job 26 on nid00315 (mriqc -i ds000171 -d anat -S sub-mdd06 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 39 running job 27 on nid00315 (mriqc -i ds000171 -d anat -S sub-mdd07 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 15 running job 33 on nid00309 (mriqc -i ds000171 -d anat -S sub-mdd13 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 13 running job 35 on nid00309 (mriqc -i ds000171 -d anat -S sub-mdd15 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 14 running job 34 on nid00309 (mriqc -i ds000171 -d anat -S sub-mdd14 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 12 running job 36 on nid00309 (mriqc -i ds000171 -d anat -S sub-mdd16 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 7 running job 30 on nid00307 (mriqc -i ds000171 -d anat -S sub-mdd10 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 6 running job 29 on nid00307 (mriqc -i ds000171 -d anat -S sub-mdd09 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 4 running job 32 on nid00307 (mriqc -i ds000171 -d anat -S sub-mdd12 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 5 running job 31 on nid00307 (mriqc -i ds000171 -d anat -S sub-mdd11 -o ds151_mriqc.out -w ds151_mriqc.wrk)
grep: invalid max count
Launcher: Task 23 running job 38 on nid00311 (mriqc -i ds000171 -d anat -S sub-mdd18 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 22 running job Done on nid00311 ()
Launcher: Task 21 running job 37 on nid00311 (mriqc -i ds000171 -d anat -S sub-mdd17 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Task 20 running job 39 on nid00311 (mriqc -i ds000171 -d anat -S sub-mdd19 -o ds151_mriqc.out -w ds151_mriqc.wrk)
Launcher: Job Done completed in 0 seconds.
Launcher: Task 22 done. Exiting.
Traceback (most recent call last):
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/bin/mriqc", line 9, in <module>
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/utils/mriqc_run.py", line 99, in main
    os.makedirs(log_dir)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'ds151_mriqc.wrk_log'
Launcher: Job 39 completed in 90 seconds.
Launcher: Task 20 done. Exiting.
Traceback (most recent call last):
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/bin/mriqc", line 9, in <module>
Traceback (most recent call last):
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/bin/mriqc", line 9, in <module>
Traceback (most recent call last):
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/bin/mriqc", line 9, in <module>
Traceback (most recent call last):
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/bin/mriqc", line 9, in <module>
Traceback (most recent call last):
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/bin/mriqc", line 9, in <module>
Traceback (most recent call last):
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/bin/mriqc", line 9, in <module>
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/utils/mriqc_run.py", line 124, in main
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/utils/mriqc_run.py", line 124, in main
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/utils/mriqc_run.py", line 124, in main
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/utils/mriqc_run.py", line 124, in main
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/utils/mriqc_run.py", line 124, in main
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/utils/mriqc_run.py", line 124, in main
    run_id=opts.run_id, settings=settings)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/core.py", line 41, in ms_anat
    run_id=opts.run_id, settings=settings)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/core.py", line 41, in ms_anat
    run_id=opts.run_id, settings=settings)
    run_id=opts.run_id, settings=settings)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/core.py", line 41, in ms_anat
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/core.py", line 41, in ms_anat
    run_id=opts.run_id, settings=settings)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/core.py", line 41, in ms_anat
    run_id=opts.run_id, settings=settings)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/core.py", line 41, in ms_anat
    anat_qc = anat_qc_workflow(settings=settings)
    anat_qc = anat_qc_workflow(settings=settings)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/anatomical.py", line 42, in anat_qc_workflow
    anat_qc = anat_qc_workflow(settings=settings)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/anatomical.py", line 42, in anat_qc_workflow
    anat_qc = anat_qc_workflow(settings=settings)
    anat_qc = anat_qc_workflow(settings=settings)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/anatomical.py", line 42, in anat_qc_workflow
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/anatomical.py", line 42, in anat_qc_workflow
    anat_qc = anat_qc_workflow(settings=settings)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/anatomical.py", line 42, in anat_qc_workflow
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/mriqc/mriqc/workflows/anatomical.py", line 42, in anat_qc_workflow
    os.makedirs(deriv_dir)
    os.makedirs(deriv_dir)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/lib/python2.7/os.py", line 157, in makedirs
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    os.makedirs(deriv_dir)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'ds151_mriqc.wrk/derivatives'
    os.makedirs(deriv_dir)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    os.makedirs(deriv_dir)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    os.makedirs(deriv_dir)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/opt/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
    mkdir(name, mode)
OSErrorOSError: [Errno 17] File exists: 'ds151_mriqc.wrk/derivatives'
    mkdir(name, mode)
: [Errno 17] File exists: 'ds151_mriqc.wrk/derivatives'
OSError: [Errno 17] File exists: 'ds151_mriqc.wrk/derivatives'
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'ds151_mriqc.wrk/derivatives'
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'ds151_mriqc.wrk/derivatives'
Launcher: Job 12 completed in 93 seconds.
Launcher: Job 29 completed in 93 seconds.
Launcher: Job 8 completed in 93 seconds.
Launcher: Job 26 completed in 93 seconds.
Launcher: Job 15 completed in 93 seconds.
Launcher: Task 17 done. Exiting.
Launcher: Job 13 completed in 93 seconds.
Launcher: Task 27 done. Exiting.
Launcher: Task 36 done. Exiting.
Launcher: Task 30 done. Exiting.
Launcher: Task 29 done. Exiting.
Launcher: Task 6 done. Exiting.
160526-11:55:16,133 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,134 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,137 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,138 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,168 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,168 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,160 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,171 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,162 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,175 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,175 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,172 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,163 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,176 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
160526-11:55:16,180 interface WARNING:
	 AFNI is outdated, detected version AFNI_16.0.00 and <!DOCTYPE is available.
```
