### ISSUE TITLE
[BUG] Cannot cast ufunc subtract output in ComputeDVARS

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#144]
On ds005:

```
160730-02:00:52,840 workflow ERROR:
	 ['Node ComputeDVARS.a00 failed to run on host nid00602.']
160730-02:00:52,841 workflow INFO:
	 Saving crash info to /scratch/03843/crn_plab/crn_plab/job-6856540562201907686-242ac114-0001-007-crn-automated-job/sjob-6856540562201907686-242ac114-0001-007-000/workdir_log/crash-20160730-020052-crn_plab-ComputeDVARS.a00-20137099-1ea0-441a-bcce-b384b62ae5c6.pklz
160730-02:00:52,841 workflow INFO:
	 Traceback (most recent call last):
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 49, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 496, in _run_interface
    raise out
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('<i2') with casting rule 'same_kind'
Interface Function failed to run.
```

**Comment by oesteban** [comment]
```
160730-04:29:13,602 workflow ERROR:
	 ['Node ComputeDVARS.a11 failed to run on host nid00140.']
160730-04:29:13,603 workflow INFO:
	 Saving crash info to /scratch/03843/crn_plab/crn_plab/job-7078397129346051610-242ac114-0001-007-crn-automated-job/sjob-7078397129346051610-242ac114-0001-007-000/workdir_log/crash-20160730-042913-crn_plab-ComputeDVARS.a11-6e678526-24b0-439b-b422-210a124d417a.pklz
160730-04:29:13,603 workflow INFO:
	 Traceback (most recent call last):
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 49, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home1/03843/crn_plab/workspace/mriqc/mriqc/interfaces/functional.py", line 41, in _run_interface
    output_all=self.inputs.output_all)
  File "/home1/03843/crn_plab/workspace/mriqc/mriqc/qc/functional.py", line 156, in compute_dvars
    mfunc -= mfunc.mean(axis=1)[..., np.newaxis]
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('<i2') with casting rule 'same_kind'
Interface ComputeDVARS failed to run. 
```
