### ISSUE TITLE
Improper string formatting

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#148]
https://github.com/poldracklab/mriqc/blob/f6a0afbfd8064f82cb9e76a6a3a8c3a8a27c89f3/mriqc/utils/mriqc_run.py#L138

The string is missing the .format( ) call.

**Comment by oesteban** [comment]
Does it break? In principle, logging should accept that formatting.

**Comment by jvarada** [comment]
It does give an error traceback:

--- Logging error ---
Traceback (most recent call last):
  File "/Users/varadajc/anaconda/envs/qc/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/Users/varadajc/anaconda/envs/qc/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/Users/varadajc/anaconda/envs/qc/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/Users/varadajc/anaconda/envs/qc/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/varadajc/anaconda/envs/qc/bin/mriqc", line 11, in <module>
    sys.exit(main())
  File "/Users/varadajc/anaconda/envs/qc/lib/python3.5/site-packages/mriqc/utils/mriqc_run.py", line 138, in main
    LOGGER.warn('No {} scans were found in {}', dtype, settings['bids_root'])
Message: 'No {} scans were found in {}'
Arguments: ('func', '/Users/varadajc/Documents/xscanner/xscanner_bids')

**Comment by jvarada** [comment]
I think if the opening brackets were escaped, it wouldn't throw an error. As it is, the python interpreter looks for the parameter substitutions and fails when it doesn't find them.

**Comment by oesteban** [comment]
I guess python 2.7 is not accepting the '{}'  substitutions. Could you please check if '%s' work and send a PR? I can do it myself, but since you discovered this problem that would be a great contribution :)

(the logging function should take the parameters as arguments: https://docs.python.org/2/library/logging.html#logging.Logger.warning)

**Comment by jvarada** [comment]
I'm running on Python 3, but I can check on Python 2.

**Comment by oesteban** [comment]
ok, no, that's even better. Does it work with %s in py3?
