### ISSUE TITLE
MRIQC fails on ds003

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#165]
```
	 Saving crash info to /scratch/03843/crn_plab/crn_plab/job-8941282362378612250-242ac115-0001-007-crn-automated-job/out/logs/crash-20160913-191726-crn_plab-measures.a1-3394e134-8754-48b5-9220-5ba9d644b758.pklz
160913-19:17:26,606 workflow INFO:
	 Traceback (most recent call last):
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 49, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
    runtime = self._run_wrapper(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1000, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/mriqc-0.8.6a2-py2.7.egg/mriqc/interfaces/qc.py", line 121, in _run_interface
    erodemask=not self.inputs.testing)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/mriqc-0.8.6a2-py2.7.egg/mriqc/qc/anatomical.py", line 254, in art_qi2
    thresh = np.percentile(data[data > 0], 99.5)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3699, in percentile
    interpolation=interpolation)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3425, in _ureduce
    r = func(a, **kwargs)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3816, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/miniconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 124, in take
    return take(indices, axis, out, mode)
IndexError: cannot do a non-empty take from an empty axes.
Interface StructuralQC failed to run. 
```
[logfile.txt](https://github.com/poldracklab/mriqc/files/471203/logfile.txt)

**Comment by oesteban** [comment]
Thanks a lot, I was after some dataset with this problem. Basically, this happens when the noise in the background is very small or has been removed. I'll see what can we do.
