### ISSUE TITLE
traits issue recognizing ants-settings file

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#167]
```
Traceback (most recent call last):
  File "/Users/varadajc/anaconda/envs/mriqc-dev/bin/mriqc", line 9, in <module>
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
  File "/Users/varadajc/dev/mriqc/mriqc/utils/mriqc_run.py", line 154, in main
    run_id=opts.run_id, settings=settings)
  File "/Users/varadajc/dev/mriqc/mriqc/workflows/core.py", line 42, in ms_anat
    anat_qc = anat_qc_workflow(settings=settings)
  File "/Users/varadajc/dev/mriqc/mriqc/workflows/anatomical.py", line 71, in anat_qc_workflow
    amw = airmsk_wf(settings=settings)
  File "/Users/varadajc/dev/mriqc/mriqc/workflows/anatomical.py", line 276, in airmsk_wf
    from_file=ants_settings), name='normalize')
  File "/Users/varadajc/anaconda/envs/mriqc-dev/lib/python3.5/site-packages/nipype/interfaces/ants/base.py", line 44, in __init__
    super(ANTSCommand, self).__init__(**inputs)
  File "/Users/varadajc/anaconda/envs/mriqc-dev/lib/python3.5/site-packages/nipype/interfaces/base.py", line 1565, in __init__
    super(CommandLine, self).__init__(**inputs)
  File "/Users/varadajc/anaconda/envs/mriqc-dev/lib/python3.5/site-packages/nipype/interfaces/base.py", line 765, in __init__
    self.inputs = self.input_spec(**inputs)
  File "/Users/varadajc/anaconda/envs/mriqc-dev/lib/python3.5/site-packages/nipype/interfaces/base.py", line 362, in __init__
    super(BaseTraitedSpec, self).__init__(**kwargs)
traits.trait_errors.TraitError: Cannot set the undefined 'from_file' attribute of a 'RegistrationInputSpec' object.
```

**Comment by oesteban** [comment]
Looks like nipype is not up to master.

BTW, I'm working on the python 3 compatibility. I don't think it will work well before #138 gets merged.

**Comment by jvarada** [comment]
Updating nipype fixed this issue.
