### ISSUE TITLE
Problem parsing ants settings json file

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#169]
When running the ants Registration node in the anatomical workflow, I get the following error:

```
Traceback (most recent call last):
  File "/Users/varadajc/dev/nipype/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/Users/varadajc/dev/nipype/nipype/pipeline/engine/nodes.py", line 377, in run
    self._run_interface()
  File "/Users/varadajc/dev/nipype/nipype/pipeline/engine/nodes.py", line 487, in _run_interface
    self._result = self._run_command(execute)
  File "/Users/varadajc/dev/nipype/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    cmd = self._interface.cmdline
  File "/Users/varadajc/dev/nipype/nipype/interfaces/base.py", line 1663, in cmdline
    allargs = self._parse_inputs()
  File "/Users/varadajc/dev/nipype/nipype/interfaces/base.py", line 1900, in _parse_inputs
    arg = self._format_arg(name, spec, value)
  File "/Users/varadajc/dev/nipype/nipype/interfaces/ants/registration.py", line 823, in _format_arg
    return self._format_registration()
  File "/Users/varadajc/dev/nipype/nipype/interfaces/ants/registration.py", line 749, in _format_registration
    for metric in self._format_metric(ii):
  File "/Users/varadajc/dev/nipype/nipype/interfaces/ants/registration.py", line 665, in _format_metric
    weight=self.inputs.metric_weight[index],
IndexError: list index out of range
```

From the nipype crash report, it looks like the settings that the module executed were:

```
Node inputs:

args = <undefined>
collapse_output_transforms = False
convergence_threshold = [1e-06]
convergence_window_size = [10]
dimension = 3
environ = {'NSLOTS': '4'}
fixed_image = ['/Users/varadajc/.cache/mriqc/mni_template/MNI152_T1_1mm.nii.gz']
fixed_image_mask = /Users/varadajc/.cache/mriqc/mni_template/MNI152_T1_1mm_brain_mask.nii.gz
float = True
ignore_exception = False
initial_moving_transform = <undefined>
initial_moving_transform_com = True
initialize_transforms_per_stage = False
interpolation = Linear
interpolation_parameters = <undefined>
invert_initial_moving_transform = <undefined>
metric = ['Mattes', 'Mattes', ['Mattes', 'CC']]
metric_item_trait = <undefined>
metric_stage_trait = <undefined>
metric_weight = [1.0]
metric_weight_item_trait = <undefined>
metric_weight_stage_trait = <undefined>
moving_image = ['/Users/varadajc/Documents/xscanner/work/anatMRIQC/MRIQC_Anat/_data_sub-0001.ses-AWP45160.run-01/Bias/sub-0001_ses-AWP45160_run-01_T1w_out_corrected.nii.gz']
moving_image_mask = /Users/varadajc/Documents/xscanner/work/anatMRIQC/MRIQC_Anat/AFNISkullStripWorkflow/_data_sub-0001.ses-AWP45160.run-01/binarize/sub-0001_ses-AWP45160_run-01_T1w_out_calc_thresh.nii.gz
num_threads = 4
number_of_iterations = [[10000, 11110, 11110], [10000, 11110, 11110], [100, 30, 20]]
output_inverse_warped_image = <undefined>
output_transform_prefix = transform
output_warped_image = True
radius_bins_item_trait = <undefined>
radius_bins_stage_trait = <undefined>
radius_or_number_of_bins = [5]
restore_state = <undefined>
sampling_percentage = [0.3, 0.3, [None, None]]
sampling_percentage_item_trait = <undefined>
sampling_percentage_stage_trait = <undefined>
sampling_strategy = ['Regular', 'Regular', [None, None]]
sampling_strategy_item_trait = <undefined>
sampling_strategy_stage_trait = <undefined>
save_state = <undefined>
shrink_factors = [[3, 2, 1], [3, 2, 1], [4, 2, 1]]
sigma_units = ['vox', 'vox', 'vox']
smoothing_sigmas = [[4.0, 2.0, 1.0], [4.0, 2.0, 1.0], [1.0, 0.5, 0.0]]
terminal_output = stream
transform_parameters = [(0.1,), (0.1,), (0.2, 3.0, 0.0)]
transforms = ['Rigid', 'Affine', 'SyN']
use_estimate_learning_rate_once = [True, True, True]
use_histogram_matching = True
winsorize_lower_quantile = 0.0
winsorize_upper_quantile = 1.0
write_composite_transform = False
```

which are not the same as the settings in the t1-mni_registration.json file.

I looked into what's happening in the debugger and it seems to be a bug within nipype's `load_input_from_json(...)` or with how that method is called within the BaseInterface class. The constructor in the BaseInterface class is calling the method with "overwrite=False", so the values within the json file that already exist do not get updated. Is this a nipype bug or is there a way to fix this within mriqc?

**Comment by jvarada** [comment]
Never mind, my nipype install was seriously messed up.
