### ISSUE TITLE
Frame Displacement Computation Error

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#186]
Getting this when running the functional workflow:

`Traceback (most recent call last):
  File "/data/varadajc/7T_results/work/funcMRIQC/batch/pyscript_20160927_161146_funcMRIQC.fMRIQC_ComputeFD.a8.py", line 32, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/varadajc/Libs/nipype/nipype/pipeline/engine/nodes.py", line 377, in run
    self._run_interface()
  File "/home/varadajc/Libs/nipype/nipype/pipeline/engine/nodes.py", line 487, in _run_interface
    self._result = self._run_command(execute)
  File "/home/varadajc/Libs/nipype/nipype/pipeline/engine/nodes.py", line 617, in _run_command
    result = self._interface.run()
  File "/home/varadajc/Libs/nipype/nipype/interfaces/base.py", line 1082, in run
    runtime = self._run_wrapper(runtime)
  File "/home/varadajc/Libs/nipype/nipype/interfaces/base.py", line 1030, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/varadajc/Libs/nipype/nipype/algorithms/confounds.py", line 250, in _run_interface
    diff = mpars[:-1, :] - mpars[1:, :]
IndexError: too many indices for array
Interface FramewiseDisplacement failed to run. `

Any ideas?

**Comment by jvarada** [comment]
Could it be that you're passing the output of Mat2MovPar (which computes the FD) to the ComputeFD node?

**Comment by oesteban** [comment]
I'll look into that, your hypothesis looks pretty likely to me.

**Comment by jvarada** [comment]
Pull request with fix: #189

**Comment by jvarada** [comment]
Merged with #189
