### ISSUE TITLE
Report running attempts to run before workflow is complete when using SLURMGraph

### ISSUE THREAD

**Issue by wtriplett** [poldracklab/mriqc#27]
The SlurmGraph plugin works very well! One thing I noticed is that it appears to submit the jobs properly then attempts to run reports while the processing jobs are still queued. Also, this PR is being used for LS5: https://github.com/nipy/nipype/pull/1330

**plugin config**

    plugin: SLURMGraph
    plugin_args: { 
    dont_resubmit_completed_jobs: True, 
    sbatch_args: '--quiet -p normal -N 1 -n 1 -t 00:10:00'
    }

**stdout**

    160124-17:21:22,137 workflow INFO:
             ['check', 'execution', 'logging']
    160124-17:21:25,951 workflow INFO:
             submitted all jobs to queue

**stderr**

    Traceback (most recent call last):
      File "/home1/03872/wtriplet/.local/bin/mriqcp.py", line 4, in <module>
        __import__('pkg_resources').run_script('mriqc==0.0.1', 'mriqcp.py')
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 742, in run_script

      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1667, in run_script

      File "/home1/03872/wtriplet/.local/lib/python2.7/site-packages/mriqc-0.0.1-py2.7.egg/EGG-INFO/scripts/mriqcp.py", line 124, in <module>
        reports = workflow_report(out_csv, 'anatomical', settings=settings)
      File "/home1/03872/wtriplet/.local/lib/python2.7/site-packages/mriqc-0.0.1-py2.7.egg/mriqc/reports.py", line 37, in workflow_report
        df = pd.read_csv(in_csv, dtype={'subject': str}).sort(
      File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 498, in parser_f
        return _read(filepath_or_buffer, kwds)
      File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 275, in _read
        parser = TextFileReader(filepath_or_buffer, **kwds)
      File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 590, in __init__
        self._make_engine(self.engine)
      File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 731, in _make_engins  f._engine = CParserWrapper(self.f, **self.options)
      File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1103, in __init__
        self._reader = _parser.TextReader(src, **kwds)
      File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3246)
      File "pandas/parser.pyx", line 591, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6111)
    IOError: File /corral-repl/utexas/poldracklab/openfmri/inprocess/ds030_QAP/OUT/aMRIQC.csv does not exist

**Comment by chrisfilo** [comment]
Maybe the solution would be to connect the outputs of qc workflow to report
writing workflow and run this as one big workflow?

The SlurmGraph plugin works very well! One thing I noticed is that it
appears to submit the jobs properly then attempts to run reports while the
processing jobs are still queued. Also, this PR is being used for LS5:
nipy/nipype#1330 <https://github.com/nipy/nipype/pull/1330>

*plugin config*

plugin: SLURMGraph
plugin_args: {
dont_resubmit_completed_jobs: True,
sbatch_args: '--quiet -p normal -N 1 -n 1 -t 00:10:00'
}

*stdout*

160124-17:21:22,137 workflow INFO:
         ['check', 'execution', 'logging']
160124-17:21:25,951 workflow INFO:
         submitted all jobs to queue

*stderr*

Traceback (most recent call last):
  File "/home1/03872/wtriplet/.local/bin/mriqcp.py", line 4, in <module>
    __import__('pkg_resources').run_script('mriqc==0.0.1', 'mriqcp.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line
742, in run_script

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line
1667, in run_script

  File "/home1/03872/wtriplet/.local/lib/python2.7/site-packages/mriqc-0.0.1-py2.7.egg/EGG-INFO/scripts/mriqcp.py",
line 124, in <module>
    reports = workflow_report(out_csv, 'anatomical', settings=settings)
  File "/home1/03872/wtriplet/.local/lib/python2.7/site-packages/mriqc-0.0.1-py2.7.egg/mriqc/reports.py",
line 37, in workflow_report
    df = pd.read_csv(in_csv, dtype={'subject': str}).sort(
  File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py",
line 498, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py",
line 275, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py",
line 590, in __init__
    self._make_engine(self.engine)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py",
line 731, in _make_engins  f._engine = CParserWrapper(self.f,
**self.options)
  File "/corral-repl/utexas/poldracklab/users/wtriplet/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py",
line 1103, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 353, in
pandas.parser.TextReader.__cinit__ (pandas/parser.c:3246)
  File "pandas/parser.pyx", line 591, in
pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6111)
IOError: File /corral-repl/utexas/poldracklab/openfmri/inprocess/ds030_QAP/OUT/aMRIQC.csv
does not exist

—
Reply to this email directly or view it on GitHub
<https://github.com/poldracklab/mriqc/issues/27>.

**Comment by oesteban** [comment]
Hi guys, thanks a lot for the comments, you are actually talking about the same issue, and you are right of course. I will take on this ASAP
