### ISSUE TITLE
[singularity] User settings in python trespass into the container

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#292]
As reported by @jokedurnez :

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/root/src/mriqc/mriqc/utils/mriqc_run.py", line 20, in <module>
    from mriqc.workflows import core as mwc
  File "/root/src/mriqc/mriqc/workflows/__init__.py", line 10, in <module>
    from mriqc.workflows.core import ms_anat, ms_func
  File "/root/src/mriqc/mriqc/workflows/core.py", line 17, in <module>
    from nipype.pipeline import engine as pe
  File "/home/jdurnez/.local/lib/python2.7/site-packages/nipype/__init__.py", line 71, in <module>
    from .pipeline import Node, MapNode, JoinNode, Workflow
  File "/home/jdurnez/.local/lib/python2.7/site-packages/nipype/pipeline/__init__.py", line 10, in <module>
    from .engine import Node, MapNode, JoinNode, Workflow
  File "/home/jdurnez/.local/lib/python2.7/site-packages/nipype/pipeline/engine/__init__.py", line 12, in <module>
    from .workflows import Workflow
  File "/home/jdurnez/.local/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 41, in <module>
    from ...interfaces.base import (traits, InputMultiPath, CommandLine,
  File "/home/jdurnez/.local/lib/python2.7/site-packages/nipype/interfaces/__init__.py", line 13, in <module>
    from .utility import IdentityInterface, Rename, Function, Select, Merge
  File "/home/jdurnez/.local/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 28, in <module>
    from ..testing import assert_equal
  File "/home/jdurnez/.local/lib/python2.7/site-packages/nipype/testing/__init__.py", line 29, in <module>
    from nose.tools import *
ImportError: No module named nose.tools
```

This is likely to be solved setting the [PYTHONNOUSERSITE](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONNOUSERSITE) environment variable.

**Comment by oesteban** [comment]
-> poldracklab_mriqc_0.8.8rc13-2016-11-15-eb70b73d1783.img

**Comment by yarikoptic** [comment]
do you guys provide mriqc singularity images publicly somewhere?

**Comment by oesteban** [comment]
Hi @yarikoptic, no we don't. But you can do ```make singularity``` at the top-level folder to do it. The command line you'd need is here https://github.com/poldracklab/mriqc/blob/master/Makefile#L58
