### ISSUE TITLE
Singular matrix computing DVARS

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#308]
DS005 - sub-01_task-mixedgamblestask_run-01_bold.nii.gz, sub-04_task-mixedgamblestask_run-02_bold.nii.gz

```
Traceback (most recent call last):
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nipype-0.13.0_g865ad49.dev-py2.7.egg/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nipype-0.13.0_g865ad49.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 367, in run
    self._run_interface()
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nipype-0.13.0_g865ad49.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 477, in _run_interface
    self._result = self._run_command(execute)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nipype-0.13.0_g865ad49.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nipype-0.13.0_g865ad49.dev-py2.7.egg/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nipype-0.13.0_g865ad49.dev-py2.7.egg/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nipype-0.13.0_g865ad49.dev-py2.7.egg/nipype/algorithms/confounds.py", line 128, in _run_interface
    remove_zerovariance=self.inputs.remove_zerovariance)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nipype-0.13.0_g865ad49.dev-py2.7.egg/nipype/algorithms/confounds.py", line 598, in compute_dvars
    ar1 = np.apply_along_axis(AR_est_YW, 1, mfunc, 1)[:, 0]
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 128, in apply_along_axis
    res = func1d(arr[tuple(i.tolist())], *args, **kwargs)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nitime-0.6-py2.7.egg/nitime/algorithms/autoregressive.py", line 96, in AR_est_YW
    ak = linalg.solve(Tm, y)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/scipy/linalg/basic.py", line 103, in solve
    raise LinAlgError("singular matrix")
LinAlgError: singular matrix
Interface ComputeDVARS failed to run.
```

**Comment by oesteban** [comment]
Just run those two subjects with 0.9.5. No problem at all.
