### ISSUE TITLE
[BUG] Nibabel problem with compression (ABIDE 50709)

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#319]
@chrisfilo - this was the only crashfile after processing (both functional and anatomical) the whole ABIDE dataset :)

```
File: /scratch/03763/oesteban/work/abide-3/out/logs/crash-20161202-173056-oesteban-reorient_and_discard.a0-ee105365-dde1-4bed-9137-cb70be1d5566.pklz
Node: workflow_enumerator.funcMRIQC.reorient_and_discard.a0
Working directory: /scratch/03763/oesteban/work/abide-3/work/workflow_enumerator/funcMRIQC/_in_file_..scratch..03763..oesteban..work..abide-2..data..sub-50709..func..sub-50709_task-rest_bold.nii.gz/reorient_and_discard


Node inputs:

function_str = def reorient_and_discard_non_steady(in_file):
    import nibabel as nb
    import os
    import numpy as np
    import nibabel as nb
    from statsmodels.robust.scale import mad

    _, outfile = os.path.split(in_file)

    nii = nb.as_closest_canonical(nb.load(in_file))
    in_data = nii.get_data()
    data = in_data[:, :, :, :50]
    timeseries = data.max(axis=0).max(axis=0).max(axis=0)
    outlier_timecourse = (timeseries - np.median(timeseries)) / mad(
        timeseries)
    exclude_index = 0
    for i in range(10):
        if outlier_timecourse[i] > 10:
            exclude_index += 1
        else:
            break

    nb.Nifti1Image(in_data[:, :, :, exclude_index:], nii.affine).to_filename(outfile)
    return exclude_index, os.path.abspath(outfile)

ignore_exception = False
in_file = /scratch/03763/oesteban/work/abide-2/data/sub-50709/func/sub-50709_task-rest_bold.nii.gz



Traceback:
Traceback (most recent call last):
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nipype-0.13.0_g8ddca5a.dev-py2.7.egg/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nipype-0.13.0_g8ddca5a.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 367, in run
    self._run_interface()
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nipype-0.13.0_g8ddca5a.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 477, in _run_interface
    self._result = self._run_command(execute)
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nipype-0.13.0_g8ddca5a.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nipype-0.13.0_g8ddca5a.dev-py2.7.egg/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nipype-0.13.0_g8ddca5a.dev-py2.7.egg/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nipype-0.13.0_g8ddca5a.dev-py2.7.egg/nipype/interfaces/utility.py", line 498, in _run_interface
    out = function_handle(**args)
  File "<string>", line 10, in reorient_and_discard_non_steady
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/funcs.py", line 225, in as_closest_canonical
    arr = img.get_data()
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/spatialimages.py", line 572, in get_data
    data = np.asanyarray(self._dataobj)
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 533, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/arrayproxy.py", line 145, in __array__
    raw_data = self.get_unscaled()
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/arrayproxy.py", line 140, in get_unscaled
    mmap=self._mmap)
  File "/work/03843/crn_plab/anaconda/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/volumeutils.py", line 524, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/work/03843/crn_plab/anaconda/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/work/03843/crn_plab/anaconda/lib/python2.7/gzip.py", line 319, in _read
    uncompress = self.decompress.decompress(buf)
error: Error -3 while decompressing: invalid code lengths set
Interface Function failed to run.
```

**Comment by oesteban** [comment]
Didn't seem to be an issue with 0.9.3 on sherlock. Closing
