### ISSUE TITLE
BigPlot node failing

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#322]
```
161208-10:38:39,172 workflow ERROR:
	 ['Node BigPlot.a3 failed to run on host MH01918219MACLT.']
161208-10:38:39,172 workflow INFO:
	 Saving crash info to /Users/varadajc/Documents/mriqc_test/logs/crash-20161208-103839-varadajc-BigPlot.a3-50072420-4938-4c94-8cc2-07238164dfd5.pklz
161208-10:38:39,172 workflow INFO:
	 Traceback (most recent call last):
  File "/Users/varadajc/dev/mriqc/src/nipype/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/Users/varadajc/dev/mriqc/src/nipype/nipype/pipeline/engine/nodes.py", line 367, in run
    self._run_interface()
  File "/Users/varadajc/dev/mriqc/src/nipype/nipype/pipeline/engine/nodes.py", line 477, in _run_interface
    self._result = self._run_command(execute)
  File "/Users/varadajc/dev/mriqc/src/nipype/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/Users/varadajc/dev/mriqc/src/nipype/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/Users/varadajc/dev/mriqc/src/nipype/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/Users/varadajc/dev/mriqc/src/nipype/nipype/interfaces/utility.py", line 498, in _run_interface
    out = function_handle(**args)
  File "<string>", line 26, in _big_plot
  File "/Users/varadajc/anaconda/envs/mriqc/lib/python3.5/site-packages/numpy/lib/npyio.py", line 930, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/Users/varadajc/anaconda/envs/mriqc/lib/python3.5/site-packages/numpy/lib/npyio.py", line 930, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/Users/varadajc/anaconda/envs/mriqc/lib/python3.5/site-packages/numpy/lib/npyio.py", line 659, in floatconv
    return float(x)
ValueError: could not convert string to float: b'std'
Interface Function failed to run. 
```

Settings:
```
{'n_procs': 1, 'correct_slice_timing': True, 'report_dir': '/Users/varadajc/Documents/mriqc_test/reports', 'output_dir': '/Users/varadajc/Documents/mriqc_test', 'verbose_reports': False, 'bids_dir': '/Users/varadajc/Documents/mriqc_test/bids_data', 'deoblique': True, 'despike': True, 'testing': False, 'ants_nthreads': 6, 'work_dir': '/Users/varadajc/Documents/mriqc_test/work', 'hmc_afni': True, 'write_graph': True}
```

Running on Python 3.5.

**Comment by oesteban** [comment]
Found the issue: https://github.com/oesteban/nipype/commit/d066344821f7d877defb83769e7a4dc636a93503#diff-0fd61d640d7248acadd68317f5b8906f changed the headers, and now they are not prefixed with #

Last commit should fix this issue.
