### ISSUE TITLE
ImportError: No module named interfaces.registration

### ISSUE THREAD

**Issue by a-y-c** [poldracklab/mriqc#329]
Hi - I installed mriqc recently using 'pip install mriqc' and it's throwing out the error below.

```
$ mriqc -i sub-10159 -o temp_out/ -w temp_work/
Traceback (most recent call last):
  File "/u/home/FMRI/apps/gentooPrefix/usr/bin/mriqc", line 11, in <module>
    sys.exit(main())
  File "/u/home/FMRI/apps/gentooPrefix/usr/lib/python2.7/site-packages/mriqc/bin/mriqc_run.py", line 30, in main
    from mriqc.workflows.core import build_workflow
  File "/u/home/FMRI/apps/gentooPrefix/usr/lib/python2.7/site-packages/mriqc/workflows/__init__.py", line 7, in <module>
    from mriqc.workflows.anatomical import anat_qc_workflow
  File "/u/home/FMRI/apps/gentooPrefix/usr/lib/python2.7/site-packages/mriqc/workflows/anatomical.py", line 25, in <module>
    from niworkflows.interfaces.registration import RobustMNINormalizationRPT as RobustMNINormalization
ImportError: No module named interfaces.registration
```

I tried 'pip install --upgrade niworkflows' but it didn't change anything.

Any help? Thanks.

**Comment by oesteban** [comment]
Thanks for reporting.

I'll check niworkflows and the dependencies of mriqc ASAP and get back to this issue.
