### ISSUE TITLE
Failure of workflow: Bias.a0

### ISSUE THREAD

**Issue by angoldst** [poldracklab/mriqc#357]
Thanks again for the help. 

Crash report:
```
File: /share/leanew1/MKET_Study/MKET_BIDS_data_test/out/logs/crash-20170202-073924-agoldpie-Bias.a0-d4e7d498-f9f2-45de-ae88-29ae6975ebb6.pklz
Node: workflow_enumerator.anatMRIQC.Bias.a0
Working directory: /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/Bias


Node inputs:

args = <undefined>
bias_image = <undefined>
bspline_fitting_distance = <undefined>
bspline_order = <undefined>
convergence_threshold = <undefined>
dimension = 3
environ = {u'NSLOTS': u'1'}
ignore_exception = False
input_image = /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/conform/sub-346228_ses-baseline_T1w_conformed.nii
mask_image = <undefined>
n_iterations = <undefined>
num_threads = 1
output_image = <undefined>
save_bias = True
shrink_factor = <undefined>
terminal_output = stream
weight_image = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1086, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1180, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: File/Directory '/share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/Bias/sub-346228_ses-baseline_T1w_conformed_corrected.nii' not found for N4BiasFieldCorrection output 'output_image'.
Interface N4BiasFieldCorrection failed to run. 
```

In looking at the actual output from the script I also get this:
```
Description: itk::ERROR: Image(0x2b77cf0): A spacing of 0 is not allowed: Spacing is [0]
Standard error:

Return code: 1
Interface Registration failed to run. .
170202-07:40:07,270 niworkflows INFO:
	 Loading settings from file /home/agoldpie/anaconda2/lib/python2.7/site-packages/niworkflows/data/epi-mni_registration_001.json.
170202-07:40:07,275 niworkflows INFO:
	 Retry #1, commandline: 
antsRegistration --collapse-output-transforms 1 --dimensionality 3 --float 1 --initial-moving-transform [ /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/funcMRIQC/SpatialNormalization/MNIApplyMask/2mm_T2_masked.nii.gz, /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..func..sub-346228_ses-baseline_task-rest_bold.nii/EPIApplyMask/sub-346228_ses-baseline_task-rest_bold_mcf_tstat_corrected_masked.nii.gz, 1 ] --initialize-transforms-per-stage 0 --interpolation Linear --output [ epi_to_mni, epi_to_mni_Warped.nii.gz ] --transform Rigid[ 0.1 ] --metric Mattes[ /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/funcMRIQC/SpatialNormalization/MNIApplyMask/2mm_T2_masked.nii.gz, /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..func..sub-346228_ses-baseline_task-rest_bold.nii/EPIApplyMask/sub-346228_ses-baseline_task-rest_bold_mcf_tstat_corrected_masked.nii.gz, 1, 56, Random, 0.8 ] --convergence [ 10000, 1e-07, 250 ] --smoothing-sigmas 8.0vox --shrink-factors 4 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform Rigid[ 0.01 ] --metric Mattes[ /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/funcMRIQC/SpatialNormalization/MNIApplyMask/2mm_T2_masked.nii.gz, /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..func..sub-346228_ses-baseline_task-rest_bold.nii/EPIApplyMask/sub-346228_ses-baseline_task-rest_bold_mcf_tstat_corrected_masked.nii.gz, 1, 32, Random, 0.3 ] --convergence [ 100, 1e-08, 5 ] --smoothing-sigmas 4.0vox --shrink-factors 2 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform Affine[ 0.01 ] --metric Mattes[ /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/funcMRIQC/SpatialNormalization/MNIApplyMask/2mm_T2_masked.nii.gz, /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/funcMRIQC/SpatialNormalization/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..func..sub-346228_ses-baseline_task-rest_bold.nii/EPIApplyMask/sub-346228_ses-baseline_task-rest_bold_mcf_tstat_corrected_masked.nii.gz, 1, 32, Random, 0.25 ] --convergence [ 10000, 1e-08, 500 ] --smoothing-sigmas 1.0vox --shrink-factors 2 --use-estimate-learning-rate-once 0 --use-histogram-matching 1 --winsorize-image-intensities [ 0.01, 0.9995 ]  --write-composite-transform 0

```

system/pip details for reference

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
```

```alabaster==0.7.8
anaconda-client==1.4.0
anaconda-navigator==1.2.1
argcomplete==1.0.0
astropy==1.2.1
Babel==2.3.3
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.4.1
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.0
boto==2.40.0
Bottleneck==1.1.0
cdecimal==2.3
cffi==1.6.0
chest==0.2.3
click==6.6
cloudpickle==0.2.1
clyent==1.2.2
colorama==0.3.7
conda==4.2.13
conda-build==1.21.3
configobj==5.0.6
configparser==3.5.0b2
contextlib2==0.5.3
cryptography==1.4
cycler==0.10.0
Cython==0.24
cytoolz==0.8.0
dask==0.10.0
datashape==0.5.2
decorator==4.0.10
dill==0.2.5
dipy==0.11.0
docutils==0.12
dynd==0.7.3.dev1
enum34==1.1.6
et-xmlfile==1.0.1
fastcache==1.0.2
Flask==0.11.1
Flask-Cors==2.1.2
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.0.5
gevent==1.1.1
grabbit==0.0.5.1
greenlet==0.4.10
grin==1.2.1
h5py==2.6.0
HeapDict==1.0.0
html5lib==0.999999999
idna==2.1
imagesize==0.7.1
ipaddress==1.0.16
ipykernel==4.3.1
ipython==4.2.0
ipython-genutils==0.1.0
ipywidgets==4.1.1
isodate==0.5.4
itsdangerous==0.24
jdcal==1.2
jedi==0.9.0
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==4.1.1
jupyter-core==4.1.0
llvmlite==0.11.0
locket==0.2.0
lxml==3.6.0
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.2
mock==2.0.0
mpmath==0.19
mriqc==0.9.0rc1
multipledispatch==0.4.8
nb-anacondacloud==1.1.0
nb-conda==1.1.0
nb-conda-kernels==1.0.3
nbconvert==4.2.0
nbformat==4.0.1
nbpresent==3.0.2
networkx==1.11
nibabel==2.1.0
nilearn==0.2.6
nipy==0.4.0
nipype==0.13.0rc1
nitime==0.7
niworkflows==0.0.5
nltk==3.2.1
nose==1.3.7
notebook==4.2.1
numba==0.26.0
numexpr==2.6.0
numpy==1.11.1
odo==0.5.0
openpyxl==2.3.2
pandas==0.18.1
partd==0.3.4
path.py==0.0.0
pathlib2==2.1.0
patsy==0.4.1
pbr==1.10.0
pep8==1.7.0
pexpect==4.0.1
pickleshare==0.7.2
Pillow==3.2.0
ply==3.8
prov==1.5.0
psutil==4.3.0
ptyprocess==0.5.1
py==1.4.31
pyasn1==0.1.9
pybids==0.0.1
pycairo==1.10.0
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.43.0
pydicom==0.9.9
pydotplus==2.0.2
pyflakes==1.2.3
Pygments==2.1.3
pyOpenSSL==16.2.0
pyparsing==2.1.4
pytest==3.0.6
python-dateutil==2.5.3
pytz==2016.4
PyYAML==3.11
pyzmq==15.2.0
qtconsole==4.2.1
QtPy==1.0.2
rdflib==4.2.1
redis==2.10.5
requests==2.12.4
rope==0.9.4
scikit-image==0.12.3
scikit-learn==0.17.1
scipy==0.17.1
seaborn==0.7.1
simplegeneric==0.8.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
sklearn==0.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
SPARQLWrapper==1.8.0
Sphinx==1.4.1
sphinx-rtd-theme==0.1.9
spyder==2.3.9
SQLAlchemy==1.0.13
statsmodels==0.6.1
svgutils==0.2.0
sympy==1.0
tables==3.2.2
terminado==0.6
tinycss==0.4
toolz==0.8.0
tornado==4.3
traitlets==4.2.1
traits==4.6.0
unicodecsv==0.14.1
webencodings==0.5
Werkzeug==0.11.10
xlrd==1.0.0
XlsxWriter==0.9.2
xlwt==1.1.2
xvfbwrapper==0.2.9
```

**Comment by oesteban** [comment]
Could you post the output of:

```
nib-ls /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/conform/sub-346228_ses-baseline_T1w_conformed.nii
```

Or, if nib-ls is not available to you:

```
fslinfo /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/conform/sub-346228_ses-baseline_T1w_conformed.nii
```

**Comment by angoldst** [comment]
Thank you Oscar. On my way into lab now via public transit will hopefully be able to do this in about 2 hours.

Sent from my iPhone

On Feb 2, 2017, at 08:40, Oscar Esteban <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you post the output of:

nib-ls /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/conform/sub-346228_ses-baseline_T1w_conformed.nii


Or, if nib-ls is not available to you:

fslinfo /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/conform/sub-346228_ses-baseline_T1w_conformed.nii


-

**Comment by angoldst** [comment]
Sorry for the delay, today is always swamped with meetings. Tried running it again after resolving the numpy issue for the computDVARS. 

Now get this error for the Bias:
```
Node: workflow_enumerator.anatMRIQC.Bias.a0
Working directory: /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/Bias


Node inputs:

args = <undefined>
bias_image = <undefined>
bspline_fitting_distance = <undefined>
bspline_order = <undefined>
convergence_threshold = <undefined>
dimension = 3
environ = {u'NSLOTS': u'1'}
ignore_exception = False
input_image = /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/conform/sub-346228_ses-baseline_T1w_conformed.nii
mask_image = <undefined>
n_iterations = <undefined>
num_threads = 1
output_image = <undefined>
save_bias = True
shrink_factor = <undefined>
terminal_output = stream
weight_image = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1086, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/agoldpie/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1180, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: File/Directory '/share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/Bias/sub-346228_ses-baseline_T1w_conformed_corrected.nii' not found for N4BiasFieldCorrection output 'output_image'.
Interface N4BiasFieldCorrection failed to run. 

```

Here is the other file info you requested:

```
agoldpie@sni-vcs-williams:~$ fslinfo /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/conform/sub-346228_ses-baseline_T1w_conformed.nii
data_type      UINT16
dim1           256
dim2           256
dim3           176
dim4           1
datatype       512
pixdim1        0.976600
pixdim2        0.976600
pixdim3        1.000002
pixdim4        0.000000
cal_max        0.0000
cal_min        0.0000
file_type      NIFTI-1+
```

Thanks again.

**Comment by oesteban** [comment]
could you 
```
rm -r /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/conform
```

And re-run to see if there is some problem related to numpy arrays? The error of the spacing being 0 is pretty weird, especially after checking your fslinfo.

**Comment by angoldst** [comment]
Yeah definitely I can try again once I get home. I had deleted all of the work and files prior to rerunning it this last time. Will be back at my computer in 2 hours.

Sent from my iPhone

On Feb 2, 2017, at 16:05, Oscar Esteban <notifications@github.com<mailto:notifications@github.com>> wrote:


could you

rm -r /share/leanew1/MKET_Study/MKET_BIDS_data_test/work/workflow_enumerator/anatMRIQC/_in_file_..share..leanew1..MKET_Study..MKET_BIDS_data_test..sub-346228..ses-baseline..anat..sub-346228_ses-baseline_T1w.nii/conform


And re-run to see if there is some problem related to numpy arrays? The error of the spacing being 0 is pretty weird, especially after checking your fslinfo.

-

**Comment by chrisfilo** [comment]
I think the spacing thing is unrelated. It's coming from the robust mni
interface. I run into it with another subject that run to completion
without errors.

**Comment by angoldst** [comment]
This looks to be resolved as well with a new download of ants.

Thanks again.
