### ISSUE TITLE
Nibabel error in reorient_and_discard (ABIDE 50709)

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#370]
```
File: /scratch/03763/oesteban/abide-20170203/out/logs/crash-20170204-114546-oesteban-reorient_and_discard.a4-1e05657f-5e02-440b-a42c-faf3c4dd9a9d.pklz
Node: workflow_enumerator.funcMRIQC.reorient_and_discard.a4
Working directory: /scratch/03763/oesteban/abide-20170203/work/workflow_enumerator/funcMRIQC/_in_file_..scratch..03763..oesteban..abide-20170203..data..sub-50709..func..sub-50709_task-rest_bold.nii.gz/reorient_and_discard


Node inputs:

function_str = def reorient_and_discard_non_steady(in_file):
    import nibabel as nb
    import os
    import numpy as np
    import nibabel as nb
    from statsmodels.robust.scale import mad

    _, outfile = os.path.split(in_file)

    nii = nb.as_closest_canonical(nb.load(in_file))
    in_data = nii.get_data()
    data = in_data[:, :, :, :50]
    timeseries = data.max(axis=0).max(axis=0).max(axis=0)
    outlier_timecourse = (timeseries - np.median(timeseries)) / mad(
        timeseries)
    exclude_index = 0
    for i in range(10):
        if outlier_timecourse[i] > 10:
            exclude_index += 1
        else:
            break

    nb.Nifti1Image(in_data[:, :, :, exclude_index:], nii.affine).to_filename(outfile)
    return exclude_index, os.path.abspath(outfile)

ignore_exception = False
in_file = /scratch/03763/oesteban/abide-20170203/data/sub-50709/func/sub-50709_task-rest_bold.nii.gz



Traceback:
Traceback (most recent call last):
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype/interfaces/utility.py", line 498, in _run_interface
    out = function_handle(**args)
  File "<string>", line 10, in reorient_and_discard_non_steady
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/funcs.py", line 225, in as_closest_canonical
    arr = img.get_data()
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/spatialimages.py", line 572, in get_data
    data = np.asanyarray(self._dataobj)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/numpy/core/numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/arrayproxy.py", line 145, in __array__
    raw_data = self.get_unscaled()
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/arrayproxy.py", line 140, in get_unscaled
    mmap=self._mmap)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nibabel-2.1.0-py2.7.egg/nibabel/volumeutils.py", line 524, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/gzip.py", line 319, in _read
    uncompress = self.decompress.decompress(buf)
error: Error -3 while decompressing: invalid code lengths set
Interface Function failed to run.
```

**Comment by oesteban** [comment]
Duplicated of #319
