### ISSUE TITLE
Node reorient_and_discard.a0 failed to run (CRC check failed)

### ISSUE THREAD

**Issue by jokedurnez** [poldracklab/mriqc#379]
MRIQC stopped for some subjects (18.75% of the total sample).  The first trace of an error (that doesn't show up in any succesful jobs) is this:
```
workflow ERROR:
	 [u'Node reorient_and_discard.a0 failed to run on host sh-1-22.local.']
```

Full logs: [00_MRIQC.txt](https://github.com/poldracklab/mriqc/files/758581/00_MRIQC.txt) and [01_mriqc.txt](https://github.com/poldracklab/mriqc/files/758580/01_mriqc.txt)

**Comment by chrisfilo** [comment]
This is the relevant error:

```
170207-05:48:18,436 workflow INFO:
	 Executing node reorient_and_discard.a0 in dir: /scratch/PI/russpold/data/psychosis/05_mriqc/work/workflow_enumerator/funcMRIQC/_in_file_..scratch..PI..russpold..data..psychosis..03_bids..sub-S8692WOH..func..sub-S8692WOH_task-nback_run-1_bold.nii.gz/reorient_and_discard
170207-05:48:18,950 workflow ERROR:
	 [u'Node reorient_and_discard.a0 failed to run on host sh-0-31.local.']
170207-05:48:18,951 workflow INFO:
	 Saving crash info to /scratch/PI/russpold/data/psychosis/05_mriqc/out/logs/crash-20170207-054818-jdurnez-reorient_and_discard.a0-2358603f-2d70-4b18-8afa-375110920470.pklz
170207-05:48:18,951 workflow INFO:
	 Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 498, in _run_interface
    out = function_handle(**args)
  File "<string>", line 10, in reorient_and_discard_non_steady
  File "/usr/local/miniconda/lib/python2.7/site-packages/nibabel/funcs.py", line 225, in as_closest_canonical
    arr = img.get_data()
  File "/usr/local/miniconda/lib/python2.7/site-packages/nibabel/spatialimages.py", line 572, in get_data
    data = np.asanyarray(self._dataobj)
  File "/usr/local/miniconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nibabel/arrayproxy.py", line 145, in __array__
    raw_data = self.get_unscaled()
  File "/usr/local/miniconda/lib/python2.7/site-packages/nibabel/arrayproxy.py", line 140, in get_unscaled
    mmap=self._mmap)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nibabel/volumeutils.py", line 524, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/usr/local/miniconda/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/local/miniconda/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/local/miniconda/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xcce7598f != 0x891d4d62L
Interface Function failed to run. 
```

Could you check if `sub-S8692WOH_task-nback_run-1_bold.nii.gz` is not corrupted (you can load it and read the data in nibabel)?

**Comment by jokedurnez** [comment]
I can open the nifti in fslview.
But indeed if I read it with nibabel, I get this: IOError: CRC check failed 0xcce7598f != 0x891d4d62L

**Comment by oesteban** [comment]
Possibly related to #319

**Comment by chrisfilo** [comment]
This seems to me like a (minor) input data issue. I don't know why the gzip checksum is wrong and one way of trying to fix it would be to use `gunzip` and `gzip` to uncompress the file and compress it again (with correct CRC). I know this might seem like a hassle, but the issue with the data might prevent other software  (especially nibabel based) to run correctly on this data.

BTW `gunzip --test` could be also used to check CRC validity.

**Comment by jokedurnez** [comment]
I can also confirm that this problem is not only present for `Node reorient_and_discard.a0`, for example also for `Node conform.a0`.
