### ISSUE TITLE
'input_image' trait of an ApplyTransformsInputSpec

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#413]
```
2017-03-08 21:43:24,114 workflow:INFO Executing: ResampleSegmentation.a11 ID: 16
Process NonDaemonPoolWorker-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/queues.py", line 345, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/has_traits.py", line 1440, in __setstate__
    self.trait_set( trait_change_notify = trait_change_notify, **state )
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/has_traits.py", line 1543, in trait_set
    setattr( self, name, value )
  File "/root/src/nipype/nipype/interfaces/traits_extension.py", line 89, in validate
    self.error(object, name, value)
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'input_image' trait of an ApplyTransformsInputSpec instance must be an existing file name, but a value of '' <class 'str'> was specified.
```

**Comment by oesteban** [comment]
this node is defined here: https://github.com/poldracklab/mriqc/blob/master/mriqc/workflows/functional.py#L590-L593

And particularly `input_image=op.join(mni_template, '%dmm_parc.nii.gz' % resolution)`, which seems to be returning an empty string. Could you check on the inputs json file for the node?

**Comment by oesteban** [comment]
@chrisfilo any news on this? what dataset is this?

**Comment by chrisfilo** [comment]
Note to self - write down which dataset you are using when reporting issues.
