### ISSUE TITLE
Quality prediction on T1w images failing with Python 3.6

### ISSUE THREAD

**Issue by vsteiger** [poldracklab/mriqc#437]
Hi,

I'm running into an error when I start MRIQC with two sessions "T1w".
Before that the "func" run successfully through the pipeline and derivatives and reports were generated fine. MRIQC also works fine for T1w with only 1 session and both "func" and "T1w".
For all analyses I've used MRIQC 0.9.1 on ubuntu16.04

Do you have any idea how to fix this?

Please, find attached a copy of the terminal output.
[MRIQC_T1w_multiple_sessions.txt](https://github.com/poldracklab/mriqc/files/879241/MRIQC_T1w_multiple_sessions.txt)

Best,
Vivian

**Comment by oesteban** [comment]
Thanks for reporting this, we'll look into this.

**Comment by oesteban** [comment]
@vsteiger, I'm confirming your error. However it is unrelated to the multiple session feature of your dataset. It is related to the quality prediction we added in the last revision.

Will look at this ASAP.

**Comment by vsteiger** [comment]
@oesteban, thank you very much for having a look into this

**Comment by vsteiger** [comment]
Hi guys, I've tested the T1w data with MRIQC 0.9.2 again. Error messages still indicating an issue with the classifier in combination with T1w at time stamp (2017-04-17 09:18:32,053 workflow:ERROR in the attached log file).

[MRIQC_T1w_log.txt](https://github.com/poldracklab/mriqc/files/927931/MRIQC_T1w_log.txt)

**Comment by oesteban** [comment]
```
2017-04-17 10:04:42,425 workflow:INFO Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/bids.py", line 189, in _run_interface
    id_dict['mriqc_pred'] = int(cvhelper.predict(np.array([features]))[0])
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/classifier/cv.py", line 363, in predict
    return self.estimator.predict(datapoints).astype(int)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 54, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 448, in predict
    return self.best_estimator_.predict(X)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 534, in predict
    proba = self.predict_proba(X)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 573, in predict_proba
    X = self._validate_X_predict(X)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 355, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/tree/tree.py", line 365, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 407, in check_array
    _assert_all_finite(array)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 58, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
Interface IQMFileSink failed to run. 
```

**Comment by oesteban** [comment]
Since 0.9.4 MRIQC stopped supporting Python 2. However, before 0.9.6 we will not start supporting the classifier (it will be fully Python 3).

Regarding this error in the `IQMFileSink`, I'll add the problem to #377.

I'll close this one now. Feel free to open new issues if 0.9.6 does not work for you (when we release it in a couple of weeks).
