### ISSUE TITLE
AFNI - 3dTstat error

### ISSUE THREAD

**Issue by jokedurnez** [poldracklab/mriqc#446]
In version 0.9.1, using the latest docker image (poldracklab/mriqc).

This is the error I got:
```
2017-04-10 18:01:03,856 workflow:INFO Saving crash info to /scratch/PI/russpold/data/psychosis/05_mriqc/out/logs/crash-20170410-180103-jdurnez-get_mean_RPI.a4-f3305277-ee7f-4134-9153-2d6dc438141b.pklz
2017-04-10 18:01:03,856 workflow:INFO Traceback (most recent call last):
  File "/root/src/nipype/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/root/src/nipype/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/root/src/nipype/nipype/interfaces/base.py", line 1728, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/root/src/nipype/nipype/interfaces/afni/base.py", line 130, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/root/src/nipype/nipype/interfaces/base.py", line 1762, in _run_interface
    self.raise_exception(runtime)
  File "/root/src/nipype/nipype/interfaces/base.py", line 1686, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
3dTstat -mean -prefix sub-S4086UIY_task-rest_acq-RL_run-2_bold_tstat.nii.gz /scratch/PI/russpold/data/psychosis/05_mriqc/work/workflow_enumerator/funcMRIQC/fMRI_HMC_afni/_in_file_..scratch..PI..russpold..data..psychosis..03_bids..sub-S4086UIY..func..sub-S4086UIY_task-rest_acq-RL_run-2_bold.nii.gz/get_mean_RPI/sub-S4086UIY_task-rest_acq-RL_run-2_bold.nii.gz
Standard output:

Standard error:

Fatal Signal 11 (SIGSEGV) received
  3dTstat main
 Bottom of Debug Stack
** AFNI version = Debian-16.2.07~dfsg.1-1~nd80+1  Compile date = Aug 19 2016
** [[Precompiled binary Debian-x86_64-1-gnu: Aug 19 2016]]
** Program Death **
** If you report this crash to the AFNI message board,
** please copy the error messages EXACTLY, and give
** the command line you used to run the program, and
** any other information needed to repeat the problem.
** You may later be asked to upload data to help debug.
** Crash log is appended to file /home/jdurnez/.afni.crashlog

Return code: 1
Interface TStat failed to run. 
```

No memory fails this time :-p . Full logs attached.  Let me know if you need more files.

[QC.1.txt](https://github.com/poldracklab/mriqc/files/911467/QC.1.txt)

**Comment by oesteban** [comment]
Can you post the contents of your `/home/jdurnez/.afni.crashlog`?. There's something in that image that AFNI does not like.

**Comment by jokedurnez** [comment]
Here it is.
[afni-crashlog.txt](https://github.com/poldracklab/mriqc/files/911691/afni-crashlog.txt)

**Comment by oesteban** [comment]
I run MRIQC 0.9.4 on the full dataset and didn't get any errors. I'll close this for now. If it happened again, please reopen (will consider AFNI-17 for this case too).
