### ISSUE TITLE
3dSkullStrip error

### ISSUE THREAD

**Issue by jokedurnez** [poldracklab/mriqc#453]
```
2017-04-12 02:37:48,469 workflow:ERROR ['Node skullstrip.a0 failed to run on host sh-0-31.local.']
2017-04-12 02:37:48,469 workflow:INFO Saving crash info to /scratch/PI/russpold/data/psychosis/05_mriqc/out/logs/crash-20170412-023748-jdurnez-skullstrip.a0-115bb300-17cc-4a78-9dfa-c0b20f0cc88e.pklz
2017-04-12 02:37:48,470 workflow:INFO Traceback (most recent call last):
  File "/root/src/nipype/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/root/src/nipype/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/root/src/nipype/nipype/interfaces/base.py", line 1728, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/root/src/nipype/nipype/interfaces/afni/base.py", line 130, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/root/src/nipype/nipype/interfaces/base.py", line 1762, in _run_interface
    self.raise_exception(runtime)
  File "/root/src/nipype/nipype/interfaces/base.py", line 1686, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
3dSkullStrip -input /scratch/PI/russpold/data/psychosis/05_mriqc/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..scratch..PI..russpold..data..psychosis..03_bids..sub-S5139LGO..anat..sub-S5139LGO_run-1_T1w.nii.gz/skullstrip/sub-S5139LGO_run-1_T1w_conformed_corrected.nii.gz -prefix sub-S5139LGO_run-1_T1w_conformed_corrected_skullstrip.nii.gz
Standard output:

Standard error:
/usr/bin/xvfb-run: line 183: 35821 Segmentation fault      DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1

Return code: 139
Interface SkullStrip failed to run. 
```

[Crashfile](https://github.com/poldracklab/mriqc/files/917276/crash-20170412-023748-jdurnez-skullstrip.a0-115bb300-17cc-4a78-9dfa-c0b20f0cc88e.pklz.zip) and [logs](https://github.com/poldracklab/mriqc/files/917277/QC.71.txt) attached.

**Comment by jokedurnez** [comment]
In version 0.9.1, using the latest docker image (poldracklab/mriqc).

**Comment by oesteban** [comment]
This is going to be tough, but thanks for reporting!

**Comment by oesteban** [comment]
This happened with AFNI-16.2.07~dfsg.1-1~nd80+1. Currently we use 16.2.07~dfsg.1-2~nd16.04+1, so this is probably fixed. Please reopen if this happens again, and we will consider upgrading AFNI to v 17.
