### ISSUE TITLE
Interface RobustMNINormalizationRPT failed to run.

### ISSUE THREAD

**Issue by kristinasabaroedin** [poldracklab/mriqc#462]
Hi,

I am running MRICQ via docker. I keep receiving this error during spatial normalization. I've increased docker memory in preferences to 8gb.

2017-04-19 10:41:58,858 workflow:ERROR [u'Node EPI2MNI.a0 failed to run on host 414e6b7ce449.']
2017-04-19 10:41:58,862 workflow:INFO Saving crash info to /scratch/out/logs/crash-20170419-104158-root-EPI2MNI.a0-4fcfaa58-6289-40a2-83de-d6eb254d556e.pklz
2017-04-19 10:41:58,862 workflow:INFO Traceback (most recent call last):
  File "/root/src/mriqc/src/nipype/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/root/src/mriqc/src/nipype/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/root/src/mriqc/src/nipype/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/root/src/mriqc/src/nipype/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/root/src/mriqc/src/nipype/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/root/src/mriqc/src/nipype/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/root/src/mriqc/src/niworkflows/niworkflows/common/report.py", line 72, in _run_interface
    self._generate_report()
  File "/root/src/mriqc/src/niworkflows/niworkflows/common/report.py", line 175, in _generate_report
    compress=self.inputs.compress_report),
  File "/root/src/mriqc/src/niworkflows/niworkflows/viz/utils.py", line 318, in plot_registration
    svg = extract_svg(display, compress=compress)
  File "/root/src/mriqc/src/niworkflows/niworkflows/viz/utils.py", line 146, in extract_svg
    image_svg = svg_compress(image_svg, compress)
  File "/root/src/mriqc/src/niworkflows/niworkflows/viz/utils.py", line 77, in svg_compress
    if (_which('svgo') and compress == 'auto') or compress == True:
  File "/root/src/mriqc/src/niworkflows/niworkflows/viz/utils.py", line 406, in _which
    subprocess.run([cmd], stdin=subprocess.DEVNULL,
AttributeError: 'module' object has no attribute 'run'
Interface RobustMNINormalizationRPT failed to run. 

And further down the log,

2017-04-19 10:43:01,891 workflow:INFO ***********************************
2017-04-19 10:43:01,892 workflow:ERROR could not run node: workflow_enumerator.anatMRIQCT1w.SpatialNormalization.a0
2017-04-19 10:43:01,892 workflow:INFO crashfile: /scratch/out/logs/crash-20170419-102325-root-SpatialNormalization.a0-f1c571e3-2fc4-46cb-a34e-e775142a3e8f.pklz
2017-04-19 10:43:01,894 workflow:ERROR could not run node: workflow_enumerator.funcMRIQC.SpatialNormalization.EPI2MNI.a0
2017-04-19 10:43:01,895 workflow:INFO crashfile: /scratch/out/logs/crash-20170419-104158-root-EPI2MNI.a0-4fcfaa58-6289-40a2-83de-d6eb254d556e.pklz
2017-04-19 10:43:01,896 workflow:INFO ***********************************
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
  File "/root/src/mriqc/mriqc/bin/mriqc_run.py", line 254, in main
    workflow.run(**plugin_settings)
  File "/root/src/mriqc/src/nipype/nipype/pipeline/engine/workflows.py", line 583, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/root/src/mriqc/src/nipype/nipype/pipeline/plugins/linear.py", line 61, in run
    report_nodes_not_run(notrun)
  File "/root/src/mriqc/src/nipype/nipype/pipeline/plugins/base.py", line 95, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '

The full log is attached. 

Thanks.

[mricq_200417.txt](https://github.com/poldracklab/mriqc/files/938907/mricq_200417.txt)

**Comment by chrisfilo** [comment]
This should've been fixed in MRIQC 0.9.2. Please try this version (replace `poldracklab/mriqc:latest` with `poldracklab/mriqc:0.9.2`).

**Comment by kristinasabaroedin** [comment]
Thanks, it works. It takes ~4 hours to run a single subject's T1 and bold. Is this normal?

**Comment by chrisfilo** [comment]
I'm glad it worked!

The computational speed  depends on a) number of runs b) number of TRs in bold files c) resolution d) number of CPU cores available (you can modify this in docker settings). I've seen datasets when running one subject can take that much time.

We are planning to speed certain steps up so things might get better.
