### ISSUE TITLE
problem generating (or reading?) summary CSV files

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#551]
```
Traceback (most recent call last):
  File "/home/varadajc/.conda/envs/mriqc_test/bin/mriqc", line 11, in <module>
    sys.exit(main())
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 363, in main
    out_file=out_html)
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/mriqc/reports/group.py", line 117, in gen_html
    dataframe['label'] = dataframe[id_labels].apply(_format_labels, axis=1)
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/pandas/core/frame.py", line 4262, in apply
    ignore_failures=ignore_failures)
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/pandas/core/frame.py", line 4358, in _apply_standard
    results[i] = func(v)
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/mriqc/reports/group.py", line 184, in _format_labels
    if pd.notnull(row[[col_id]])[0]:
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/pandas/core/series.py", line 642, in __getitem__
    return self._get_with(key)
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/pandas/core/series.py", line 683, in _get_with
    return self.loc[key]
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/pandas/core/indexing.py", line 1541, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/pandas/core/indexing.py", line 1081, in _getitem_iterable
    self._has_valid_type(key, axis)
  File "/home/varadajc/.conda/envs/mriqc_test/lib/python3.6/site-packages/pandas/core/indexing.py", line 1418, in _has_valid_type
    (key, self.obj._get_axis_name(axis)))
KeyError: ("None of [['task_id']] are in the [index]", 'occurred at index 0')
```
Happened both when running the participant and the group workflows. HTML summary files were created correctly though.

**Comment by oesteban** [comment]
Could you share with me the csv file corresponding to this error?

**Comment by jvarada** [comment]
@oesteban Sent you the csv file and the HTML summary file generated for that subject to your e-mail.

**Comment by oesteban** [comment]
Seems to be happening to other users:

```
Traceback (most recent call last):
  File "/usr/local/mriqc/python-3.5.3/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.9.6+203.gd494c16', 'console_scripts', 'mriqc')()
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/mriqc/bin/mriqc_run.py", line 381, in main
    out_file=out_html)
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/mriqc/reports/group.py", line 117, in gen_html
    dataframe['label'] = dataframe[id_labels].apply(_format_labels, axis=1)
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/pandas/core/frame.py", line 4262, in apply
    ignore_failures=ignore_failures)
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/pandas/core/frame.py", line 4358, in _apply_standard
    results[i] = func(v)
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/mriqc/reports/group.py", line 184, in _format_labels
    if pd.notnull(row[[col_id]])[0]:
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/pandas/core/series.py", line 642, in __getitem__
    return self._get_with(key)
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/pandas/core/series.py", line 683, in _get_with
    return self.loc[key]
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1541, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1081, in _getitem_iterable
    self._has_valid_type(key, axis)
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1418, in _has_valid_type
    (key, self.obj._get_axis_name(axis)))
KeyError: ("None of [['session_id']] are in the [index]", 'occurred at index 0')
```
