### ISSUE TITLE
Cannot run MRIQC 0.9.6

### ISSUE THREAD

**Issue by mfalkiewicz** [poldracklab/mriqc#595]
When I try to run mriqc 0.9.6, I get the following error:

```
mriqc -w music_mriqc BIDS mriqc/ 'participant' 'group'

2017-07-21 12:19:20,703 root:INFO Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
2017-07-21 12:19:20,746 root:INFO Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
2017-07-21 12:19:24,328 root:INFO Participant level started...
2017-07-21 12:19:24,328 root:INFO Running MRIQC-0.9.6 (analysis_levels=[participant, group], participant_label=None)
	Settings={'despike': False, 'output_dir': '/home/mfalkiewicz/experiments/music/derivatives/mriqc', 'no_sub': False, 'testing': False, 'webapi_port': None, 'work_dir': '/home/mfalkiewicz/scratch/music_mriqc', 'report_dir': '/home/mfalkiewicz/experiments/music/derivatives/mriqc/reports', 'hmc_afni': True, 'float32': False, 'deoblique': False, 'correct_slice_timing': False, 'fft_spikes_detector': False, 'verbose_reports': False, 'n_procs': 32, 'upload_strict': False, 'webapi_url': 'https://mriqc.nimh.nih.gov/api/v1', 'write_graph': False, 'email': '', 'fd_thres': 0.2, 'bids_dir': '/home/mfalkiewicz/experiments/music/BIDS', 'hmc_fsl': False, 'ants_nthreads': 8, 'ica': False}
2017-07-21 12:19:24,329 workflow:INFO Building anatomical MRI QC workflow, datasets list: ['sub-01/anat/sub-01_acq-1_T1w.nii.gz', 'sub-01/anat/sub-01_acq-2_T1w.nii.gz', 'sub-02/anat/sub-02_acq-1_T1w.nii.gz', 'sub-02/anat/sub-02_acq-2_T1w.nii.gz', 'sub-03/anat/sub-03_acq-1_T1w.nii.gz', 'sub-03/anat/sub-03_acq-2_T1w.nii.gz', 'sub-04/anat/sub-04_acq-1_T1w.nii.gz', 'sub-04/anat/sub-04_acq-2_T1w.nii.gz', 'sub-05/anat/sub-05_acq-1_T1w.nii.gz', 'sub-05/anat/sub-05_acq-2_T1w.nii.gz', 'sub-06/anat/sub-06_acq-1_T1w.nii.gz', 'sub-06/anat/sub-06_acq-2_T1w.nii.gz', 'sub-07/anat/sub-07_acq-1_T1w.nii.gz', 'sub-07/anat/sub-07_acq-2_T1w.nii.gz', 'sub-08/anat/sub-08_acq-1_T1w.nii.gz', 'sub-08/anat/sub-08_acq-2_T1w.nii.gz', 'sub-09/anat/sub-09_acq-1_T1w.nii.gz', 'sub-09/anat/sub-09_acq-2_T1w.nii.gz', 'sub-10/anat/sub-10_acq-1_T1w.nii.gz', 'sub-10/anat/sub-10_acq-2_T1w.nii.gz', 'sub-11/anat/sub-11_acq-1_T1w.nii.gz', 'sub-11/anat/sub-11_acq-2_T1w.nii.gz', 'sub-12/anat/sub-12_acq-1_T1w.nii.gz', 'sub-12/anat/sub-12_acq-2_T1w.nii.gz', 'sub-13/anat/sub-13_acq-1_T1w.nii.gz', 'sub-13/anat/sub-13_acq-2_T1w.nii.gz', 'sub-14/anat/sub-14_acq-1_T1w.nii.gz', 'sub-14/anat/sub-14_acq-2_T1w.nii.gz', 'sub-15/anat/sub-15_acq-1_T1w.nii.gz', 'sub-15/anat/sub-15_acq-2_T1w.nii.gz', 'sub-16/anat/sub-16_acq-1_T1w.nii.gz', 'sub-16/anat/sub-16_acq-2_T1w.nii.gz', 'sub-17/anat/sub-17_acq-1_T1w.nii.gz', 'sub-17/anat/sub-17_acq-2_T1w.nii.gz', 'sub-18/anat/sub-18_acq-1_T1w.nii.gz', 'sub-18/anat/sub-18_acq-2_T1w.nii.gz', 'sub-19/anat/sub-19_acq-1_T1w.nii.gz', 'sub-19/anat/sub-19_acq-2_T1w.nii.gz', 'sub-20/anat/sub-20_acq-1_T1w.nii.gz', 'sub-20/anat/sub-20_acq-2_T1w.nii.gz', 'sub-21/anat/sub-21_acq-1_T1w.nii.gz', 'sub-21/anat/sub-21_acq-2_T1w.nii.gz', 'sub-22/anat/sub-22_acq-1_T1w.nii.gz', 'sub-22/anat/sub-22_acq-2_T1w.nii.gz', 'sub-23/anat/sub-23_acq-1_T1w.nii.gz', 'sub-23/anat/sub-23_acq-2_T1w.nii.gz', 'sub-24/anat/sub-24_acq-1_T1w.nii.gz', 'sub-24/anat/sub-24_acq-2_T1w.nii.gz', 'sub-25/anat/sub-25_acq-1_T1w.nii.gz', 'sub-25/anat/sub-25_acq-2_T1w.nii.gz', 'sub-26/anat/sub-26_acq-1_T1w.nii.gz', 'sub-26/anat/sub-26_acq-2_T1w.nii.gz', 'sub-27/anat/sub-27_acq-1_T1w.nii.gz', 'sub-27/anat/sub-27_acq-2_T1w.nii.gz', 'sub-28/anat/sub-28_acq-1_T1w.nii.gz', 'sub-28/anat/sub-28_acq-2_T1w.nii.gz', 'sub-29/anat/sub-29_acq-1_T1w.nii.gz', 'sub-29/anat/sub-29_acq-2_T1w.nii.gz', 'sub-30/anat/sub-30_acq-1_T1w.nii.gz', 'sub-30/anat/sub-30_acq-2_T1w.nii.gz', 'sub-31/anat/sub-31_acq-1_T1w.nii.gz', 'sub-31/anat/sub-31_acq-2_T1w.nii.gz', 'sub-32/anat/sub-32_acq-1_T1w.nii.gz', 'sub-32/anat/sub-32_acq-2_T1w.nii.gz', 'sub-33/anat/sub-33_acq-1_T1w.nii.gz', 'sub-33/anat/sub-33_acq-2_T1w.nii.gz', 'sub-34/anat/sub-34_acq-1_T1w.nii.gz', 'sub-35/anat/sub-35_acq-1_T1w.nii.gz', 'sub-35/anat/sub-35_acq-2_T1w.nii.gz', 'sub-36/anat/sub-36_acq-1_T1w.nii.gz', 'sub-36/anat/sub-36_acq-2_T1w.nii.gz', 'sub-37/anat/sub-37_acq-1_T1w.nii.gz', 'sub-37/anat/sub-37_acq-2_T1w.nii.gz', 'sub-38/anat/sub-38_acq-1_T1w.nii.gz', 'sub-38/anat/sub-38_acq-2_T1w.nii.gz', 'sub-39/anat/sub-39_acq-1_T1w.nii.gz', 'sub-39/anat/sub-39_acq-2_T1w.nii.gz', 'sub-40/anat/sub-40_acq-1_T1w.nii.gz', 'sub-40/anat/sub-40_acq-2_T1w.nii.gz', 'sub-41/anat/sub-41_acq-1_T1w.nii.gz', 'sub-41/anat/sub-41_acq-2_T1w.nii.gz', 'sub-42/anat/sub-42_acq-1_T1w.nii.gz', 'sub-42/anat/sub-42_acq-2_T1w.nii.gz', 'sub-43/anat/sub-43_acq-1_T1w.nii.gz', 'sub-43/anat/sub-43_acq-2_T1w.nii.gz']
Traceback (most recent call last):
  File "/home/mfalkiewicz/.local/bin/mriqc", line 11, in <module>
    sys.exit(main())
  File "/home/mfalkiewicz/.local/lib/python3.5/site-packages/mriqc/bin/mriqc_run.py", line 280, in main
    wf_list.append(build_workflow(dataset[mod], mod, settings=settings))
  File "/home/mfalkiewicz/.local/lib/python3.5/site-packages/mriqc/workflows/core.py", line 24, in build_workflow
    workflow = anat_qc_workflow(dataset, mod='T1w', settings=settings)
  File "/home/mfalkiewicz/.local/lib/python3.5/site-packages/mriqc/workflows/anatomical.py", line 94, in anat_qc_workflow
    to_ras = pe.Node(ConformImage(check_dtype=False), name='conform')
  File "/home/mfalkiewicz/.local/lib/python3.5/site-packages/nipype/pipeline/engine/nodes.py", line 159, in __init__
    raise IOError('interface must be an instance of an Interface')
OSError: interface must be an instance of an Interface
```

Any ideas what might cause it?

**Comment by chrisfilo** [comment]
Could be related to https://github.com/poldracklab/mriqc/pull/566#pullrequestreview-50231603

**Comment by oesteban** [comment]
@mfalkiewicz is this still happening with 0.9.7?

**Comment by oesteban** [comment]
Hi @mfalkiewicz, any luck with this? I'll close for now, please reopen if this is still an issue.
