### ISSUE TITLE
ImportError: cannot import name '_RepeatedSplits'

### ISSUE THREAD

**Issue by ajdneuro** [poldracklab/mriqc#618]
Hi all,

I am trying to run the classifier on my T1s with the following: mriqc_clf --load-classifier -X T1w.csv -o IDEApredictions.csv

I get the following error message: 
Traceback (most recent call last):
  File "/usr/local/mriqc/python-3.5.3/bin/mriqc_clf", line 11, in <module>
    load_entry_point('mriqc==0.9.7+22.ge7624d3', 'console_scripts', 'mriqc_clf')()
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/mriqc/bin/mriqc_clf.py", line 99, in main
    from ..classifier.helper import CVHelper
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/mriqc/classifier/helper.py", line 21, in <module>
    from .sklearn import preprocessing as mcsp
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/mriqc/classifier/sklearn/__init__.py", line 10, in <module>
    from ._split import RobustLeavePGroupsOut
  File "/usr/local/mriqc/python-3.5.3/lib/python3.5/site-packages/mriqc/classifier/sklearn/_split.py", line 11, in <module>
    from sklearn.model_selection._split import _RepeatedSplits
ImportError: cannot import name '_RepeatedSplits'

Any help on identifying a solution would be greatly appreciated! Thank you!

Best,
Alex

**Comment by ajdneuro** [comment]
Sorry scikit-learn module needed updating. This was resolved. Thanks!

**Comment by oesteban** [comment]
Thanks for providing the answer. Happy QC'ing!
