### ISSUE TITLE
Interface EstimateReferenceImage failed to run

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#631]
Several fMRI runs of ds121:

```
Node: workflow_enumerator.funcMRIQC.fMRI_HMC_afni.gen_ref
Working directory: /work/03843/crn_plab/stampede2/mriqc-0.9.7/ds121/work/workflow_enumerator/funcMRIQC/fMRI_HMC_afni/_in_file_..scratch..04623..cjmarkie..test-0.5.1..ds121_R2.0.1..sub-02..func..sub-02_task-incentiveantisaccade_run-04_bold.nii.gz/gen_ref

Node inputs:

ignore_exception = False
in_file = /work/03843/crn_plab/stampede2/mriqc-0.9.7/ds121/work/workflow_enumerator/funcMRIQC/_in_file_..scratch..04623..cjmarkie..test-0.5.1..ds121_R2.0.1..sub-02..func..sub-02_task-incentiveantisaccade_run-04_bold.nii.gz/reorient_and_discard/sub-02_task-incentiveantisaccade_run-04_bold.nii.gz
mc_method = AFNI

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1031, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/registration.py", line 314, in _run_interface
    mc_slice_nii = nb.load(res.outputs.out_file)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/loadsave.py", line 48, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/work/03843/crn_plab/stampede2/mriqc-0.9.7/ds121/work/workflow_enumerator/funcMRIQC/fMRI_HMC_afni/_in_file_..scratch..04623..cjmarkie..test-0.5.1..ds121_R2.0.1..sub-02..func..sub-02_task-incentiveantisaccade_run-04_bold.nii.gz/gen_ref/slice_volreg.nii.gz"
Interface EstimateReferenceImage failed to run.
```

@effigies any ideas about what could be the origin of this? Does it look like a niworkflow's problem to your eyes?

**Comment by effigies** [comment]
I'm going to guess you've got a `.nii` with filename `.nii.gz`.

**Comment by oesteban** [comment]
Nice tip. I hope you are right! Thanks!

**Comment by oesteban** [comment]
I couldn't replicate locally. Running again in TACC.

**Comment by oesteban** [comment]
Could not replicate with MRIQC 0.12.1. Closing.
