### ISSUE TITLE
Error creating mosaic of T2w images

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#632]
(Comes from #620)

```
Node: workflow_enumerator.anatMRIQCT2w.ReportsWorkflow.PlotMosaicNoise
Working directory: /work/workflow_enumerator/anatMRIQCT2w/ReportsWorkflow/_in_file_..data..sub-07..ses-day1..anat..sub-07_ses-day1_T2w.nii.gz/PlotMosaicNoise

Node inputs:

annotate = True
bbox_mask_file = <undefined>
cmap = viridis_r
dpi = 300
figsize = (11.69, 8.27)
ignore_exception = False
in_file = /work/workflow_enumerator/anatMRIQCT2w/_in_file_..data..sub-07..ses-day1..anat..sub-07_ses-day1_T2w.nii.gz/conform/sub-07_ses-day1_T2w_conformed.nii.gz
only_noise = True
out_file = plot_anat_mosaic2_noise.svg
title = noise enhanced

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1031, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/viz.py", line 120, in _run_interface
    annotate=self.inputs.annotate)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/viz/utils.py", line 261, in plot_mosaic
    label='%d' % z_val, annotate=annotate)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/viz/utils.py", line 49, in plot_slice
    phys_sp = np.array(spacing) * dslice.shape
ValueError: operands could not be broadcast together with shapes (2,) (3,) 
Interface PlotMosaic failed to run. 
```

**Comment by oesteban** [comment]
Should be fixed by #738.
