### ISSUE TITLE
Missing library for AFNI 3dSkullStrip in Singularity version of Docker image

### ISSUE THREAD

**Issue by justbennet** [poldracklab/mriqc#648]
I am running the Docker image from a Singularity container, and when I try to process the OpenfMRI ds008 subject 15 with mriqc, I get the following error message

```
$ singularity exec -B /home/bennet/Projects/mpeckins/MRIQC/ds008_R2.0.0:/data:ro -B $PWD/out:/out mriqc.simg  mriqc /data /out participant --participant_label sub-15
2017-10-07 14:18:56,752 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-07 14:18:57,101 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-07 14:18:57,556 mriqc.cli:WARNING No T2w scans were found in /data
2017-10-07 14:18:57,556 mriqc.cli:WARNING Anonymized quality metrics will be submitted to MRIQC's metrics repository. Use --no-sub to disable submission.
2017-10-07 14:19:40,754 workflow:ERROR ['Node skullstrip.a0 failed to run on host brainbox.']
```
The final messages from the run are:
```
2017-10-07 14:29:56,831 workflow:ERROR could not run node: workflow_enumerator.anatMRIQCT1w.AFNISkullStripWorkflow.skullstrip.a0
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.9.8.post1', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 325, in main
    workflow.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 590, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 279, in run
    report_nodes_not_run(notrun)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 101, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
```
The directory `work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-15..anat..sub-15_T1w.nii.gz/skullstrip` contains `command.txt`, which I presume is the command run by the skullstrip connector, and it contains
```
3dSkullStrip -input /home/bennet/Projects/mpeckins/MRIQC/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-15..anat..sub-15_T1w.nii.gz/skullstrip/sub-15_T1w_conformed_corrected.nii.gz -prefix sub-15_T1w_conformed_corrected_skullstrip.nii.gz
```
When I start Singularity and run that command, I get a missing library error message.
```
Singularity mriqc.simg:~/Projects/mpeckins/MRIQC> 3dSkullStrip -input /home/bennet/Projects/mpeckins/MRIQC/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-15..anat..sub-15_T1w.nii.gz/skullstrip/sub-15_T1w_conformed_corrected.nii.gz -prefix sub-15_T1w_conformed_corrected_skullstrip.nii.gz
3dSkullStrip: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
```

This agrees with the message in `out/logs/crash-20171007-141940-bennet-skullstrip.a0-92e4749c-d7dd-46ca-b3bd-457385d4fbb8.txt`, which says at the end of the Traceback,
```
RuntimeError: Command:
3dSkullStrip -input /home/bennet/Projects/mpeckins/MRIQC/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-15..anat..sub-15_T1w.nii.gz/skullstrip/sub-15_T1w_conformed_corrected.nii.gz -prefix sub-15_T1w_conformed_corrected_skullstrip.nii.gz
Standard output:
3dSkullStrip: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
```

The only `libGL*` files in `/usr/lib/x86_64-linux-gnu/` are
```
Singularity mriqc.simg:~/Projects/mpeckins/MRIQC> ls -l /usr/lib/x86_64-linux-gnu/libGL*
lrwxrwxrwx 1 root root     15 Oct 23  2015 /usr/lib/x86_64-linux-gnu/libGLU.so.1 -> libGLU.so.1.3.1
-rw-r--r-- 1 root root 453352 Oct 23  2015 /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
lrwxrwxrwx 1 root root     15 Dec  1  2013 /usr/lib/x86_64-linux-gnu/libGLw.so.1 -> libGLw.so.1.0.0
-rw-r--r-- 1 root root  26752 Dec  1  2013 /usr/lib/x86_64-linux-gnu/libGLw.so.1.0.0
```

Is this something the Docker image presumes will be supplied by the host OS?

**Comment by justbennet** [comment]
The following `mriqc.def` file works from an Ubuntu 16.04 LTS machine, where a copy of `cp /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1` was made into the directory from which the Singularity container is built.
```
Bootstrap: docker
From: poldracklab/mriqc:latest

%setup
cp /home/grundoon/Projects/MRIQC/libGL.so.1 \
   $SINGULARITY_ROOTFS/usr/lib/x86_64-linux-gnu/libGL.so.1

%post

chmod -R a+rX /usr/local/miniconda
ls -l /usr/lib/x86_64-linux-gnu/libGL.so.1
mkdir /data
```
I am then able to run
```
$ singularity exec -B $PWD/ds008_R2.0.0:/data:ro \
    -B $PWD/out:/out mriqc.simg  mriqc /data /out participant --no-sub \
    --participant_label sub-15
```
and get the `out` directory to have these contents.
```
derivatives:
sub-15_T1w.json
sub-15_task-conditionalstopsignal_run-01_bold.json
sub-15_task-conditionalstopsignal_run-02_bold.json
sub-15_task-conditionalstopsignal_run-03_bold.json
sub-15_task-stopsignal_run-01_bold.json
sub-15_task-stopsignal_run-02_bold.json
sub-15_task-stopsignal_run-03_bold.json

logs:

reports:
sub-15_T1w.html
sub-15_task-conditionalstopsignal_run-01_bold.html
sub-15_task-conditionalstopsignal_run-02_bold.html
sub-15_task-conditionalstopsignal_run-03_bold.html
sub-15_task-stopsignal_run-01_bold.html
sub-15_task-stopsignal_run-02_bold.html
sub-15_task-stopsignal_run-03_bold.html
```

**Comment by chrisfilo** [comment]
This is related https://github.com/poldracklab/mriqc/issues/567

**Comment by justbennet** [comment]
Chris,

Yes, it is!  Thanks for the pointer.  I did not see that before (obviously).  I did a bit more testing.  For this purpose, I created two Singularity images.  The first was created with the following mriqc.def
```
Bootstrap: docker
From: poldracklab/mriqc:latest

%setup
cp /home/bennet/Projects/mpeckins/MRIQC/libGL.so.1 \
   $SINGULARITY_ROOTFS/usr/lib/x86_64-linux-gnu/libGL.so.1

%post

chmod -R a+rX /usr/local/miniconda
ls -l /usr/lib/x86_64-linux-gnu/libGL.so.1
mkdir /data
```
The second was created with mriqc-test.def
```
Bootstrap: docker
From: poldracklab/mriqc:latest

%setup

%post

chmod -R a+rX /usr/local/miniconda
```
I created the images using `singularity build <img>.simg <img>.def`
```
$ ls -l *.simg
-rwxr-xr-x 1 root root 1845301279 Oct  7 13:43 mriqc.simg
-rwxr-xr-x 1 root root 1845301279 Oct  8 08:10 mriqc-test.simg
```
To facilitate debugging, I create test.sh
```
#!/bin/bash

afni -version

# locate all the installed libGL.so libraries
find /usr/lib/x86_64-linux-gnu -name libGL.so\* -ls

# what does 3dSkullStrip expect to find?
ldd $(which 3dSkullStrip) | grep GL

# clean up files so MRIQC will rerun from scratch
rm -r out/* work/*

# start the pipeline
mriqc /data /out --no-sub participant --participant_label sub-15
```
and I execute it with
```
$ singularity exec -B $PWD/ds008_R2.0.0:/data:ro -B $PWD/out:/out <img_file> bash test.sh
```

Results from todays testing are as follows

Using an unaltered Singularity build of mriqc:latest, I get

```
$ singularity exec -B $PWD/ds008_R2.0.0:/data:ro -B $PWD/out:/out mriqc-test.simg bash test.sh
Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017 (Version Debian-16.2.07~dfsg.1-5~nd16.04+1)
    14512      0 lrwxrwxrwx   1 root     root           14 Jul  6 05:22 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 -> libGL.so.1.2.0
    14513    453 -rw-r--r--   1 root     root       463424 Jul  6 05:22 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
	libGLw.so.1 => /usr/lib/x86_64-linux-gnu/libGLw.so.1 (0x00007fbffc105000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007fbffab9f000)
	libGL.so.1 (0x00007fbffa92d000)
2017-10-08 13:04:14,645 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-08 13:04:14,999 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-08 13:04:15,435 mriqc.cli:WARNING No T2w scans were found in /data
2017-10-08 13:04:57,454 workflow:ERROR ['Node skullstrip.a0 failed to run on host brainbox.']
```

Using the Singularity image into which I copy the `libGL.so.1` file into `/usr/lib/x86_64-linux-gnu`, I get
```
$ singularity exec -B $PWD/ds008_R2.0.0:/data:ro -B $PWD/out:/out mriqc.simg bash test.sh
Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017 (Version Debian-16.2.07~dfsg.1-5~nd16.04+1)
    13996    453 -rw-r--r--   1 root     root       463424 Oct  7 17:40 /usr/lib/x86_64-linux-gnu/libGL.so.1
    14514      0 lrwxrwxrwx   1 root     root           14 Jul  6 05:22 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 -> libGL.so.1.2.0
    14515    453 -rw-r--r--   1 root     root       463424 Jul  6 05:22 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
	libGLw.so.1 => /usr/lib/x86_64-linux-gnu/libGLw.so.1 (0x00007facb865e000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007facb70f8000)
	libGL.so.1 (0x00007facb6e86000)
2017-10-08 13:08:32,617 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-08 13:08:32,973 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-08 13:08:33,402 mriqc.cli:WARNING No T2w scans were found in /data
2017-10-08 13:11:07,832 niworkflows:INFO Estimating initial transform using AffineInitializer
```
which indicates that it did run `3dSkullStrip` successfully.

Does it matter that `ldd $(which 3dSkullStrip)` produces an internal location rather than a reference to a dynamically loaded library?

As a side note, running the Docker image directly without creating the image file also results in the missing library.
```
$ singularity exec -B $PWD/ds008_R2.0.0:/data:ro -B $PWD/out:/out docker://poldracklab/mriqc:latest bash test.sh
Docker image path: index.docker.io/poldracklab/mriqc:latest
Cache folder set to /home/bennet/.singularity/docker
Creating container runtime...
Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017 (Version Debian-16.2.07~dfsg.1-5~nd16.04+1)
 11162375      0 lrwxrwxrwx   1 bennet   brainbox       14 Jul  6 05:22 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 -> libGL.so.1.2.0
 11162376    456 -rw-r--r--   1 bennet   brainbox   463424 Jul  6 05:22 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
	libGLw.so.1 => /usr/lib/x86_64-linux-gnu/libGLw.so.1 (0x00007fbb11380000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007fbb0fe1a000)
	libGL.so.1 (0x00007fbb0fba8000)
2017-10-08 13:19:38,415 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-08 13:19:38,782 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-08 13:19:39,217 mriqc.cli:WARNING No T2w scans were found in /data
2017-10-08 13:20:20,219 workflow:ERROR ['Node skullstrip.a0 failed to run on host brainbox.']
```

Because of that reference to `libGL.so.1.2.0` being a location in the `3DSkullStrip` binary rather than a reference to an external library, I created a third image using mriqc-test2.def
```
Bootstrap: docker
From: poldracklab/mriqc:latest

%setup

%post

chmod -R a+rX /usr/local/miniconda
if [ -e /usr/lib/x86_64-linux-gnu/libGL.so.1 ] ; then
    ls -l /usr/lib/x86_64-linux-gnu/libGL.so.1
    rm -f /usr/lib/x86_64-linux-gnu/libGL.so.1
fi

ls -l /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0 \
   /usr/lib/x86_64-linux-gnu/libGL.so.1
ls -l /usr/lib/x86_64-linux-gnu/libGL.so.1
```
and I created the image with
```
$ sudo singularity build mriqc-test2.simg mriqc-test2.def 
```
and ran my `test.sh` file again with
```
$ singularity exec -B $PWD/ds008_R2.0.0:/data:ro -B $PWD/out:/out mriqc-test2.simg bash test.sh
Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017 (Version Debian-16.2.07~dfsg.1-5~nd16.04+1)
    13995      0 lrwxrwxrwx   1 root     root           45 Oct  8 13:42 /usr/lib/x86_64-linux-gnu/libGL.so.1 -> /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
    14513      0 lrwxrwxrwx   1 root     root           14 Jul  6 05:22 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 -> libGL.so.1.2.0
    14514    453 -rw-r--r--   1 root     root       463424 Jul  6 05:22 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
	libGLw.so.1 => /usr/lib/x86_64-linux-gnu/libGLw.so.1 (0x00007f92f19e8000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f92f0482000)
	libGL.so.1 (0x00007f92f0210000)
2017-10-08 13:44:54,326 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-08 13:44:54,679 interface:WARNING AFNI is outdated, detected version Debian-16.2.07~dfsg.1-5~nd16.04+1 and AFNI_17.2.17 is available.
2017-10-08 13:44:55,100 mriqc.cli:WARNING No T2w scans were found in /data
2017-10-08 13:47:33,393 niworkflows:INFO Estimating initial transform using AffineInitializer
```
and `3dSkullStrip` runs successfully.  Would I be correct inferring from this that the location of `/usr/lib/x86_64-linux-gnu/libGL.so.1` is fixed in the `3dSkullStrip` binary and doesn't resolve when that library moved to the `mesa` subdirectory?

**Comment by oesteban** [comment]
I am currently creating a new release that probably fixes this. I'll let you know then done.

**Comment by justbennet** [comment]
Oscar, I ran into similar issues with fmriprep.  I will add an issue there.

**Comment by mattcieslak** [comment]
Any news on this issue? I also just hit this error with 

```console
$ singularity build pl-mriqc0.11.simg docker://poldracklab/mriqc:0.11.0
$ singularity exec pl-mriqc0.11.simg 3dSkullStrip
3dSkullStrip: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory
```

**Comment by justbennet** [comment]
I ended up having to reset the permissions on several things when building a Singularity image of mriqc from Docker hub.  I used, quite a while ago this .def file.

```
Bootstrap: docker
From: poldracklab/mriqc:latest

%setup

%post

# Miniconda or Conda does not set permissions properly.  Make sure that
# everyone can read and execute what they should.
chmod -R a+rX /usr/local/miniconda

# Must make sure that the libGL.so.1 is in the right location for AFNI
if [ -e /usr/lib/x86_64-linux-gnu/libGL.so.1 ] ; then
    rm -f /usr/lib/x86_64-linux-gnu/libGL.so.1
fi
ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0 \
   /usr/lib/x86_64-linux-gnu/libGL.so.1
```
which produced a working MRIQC.

If you build the image, then

```
$ singularity shell mriqc.simg
```

you can poke around inside the library directory to see whether libgsl.so has just changed versions or what and maybe add something to a %post section to make it better.

Hope that gives you an idea or two where you might look and how to get something going.

**Comment by oesteban** [comment]
Yeah, I'm just checking on this. At first, when you run `singularity build`, you get this:

```Bash
$ singularity build mriqc-0.11.0.simg docker://poldracklab/mriqc:0.11.0
Docker image path: index.docker.io/poldracklab/mriqc:0.11.0
Cache folder set to /home/users/oesteban/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:c832082614738021cf51d68e84457a45a3f85dbe0ddbb93000c5dc5aae77fe93.tar.gz
Exploding layer: sha256:6e1a85c1d66a18674bdb5cee0a7d6b294aa4f1921d3a13074004d00485868051.tar.gz
Exploding layer: sha256:f1320ef45e201689247f36b8e037ed8de21532f952be224586cb96b43a495f36.tar.gz
Exploding layer: sha256:5a6ab6e6fbf62623bce0db5c75f3775f287c7b86cd0152b01ab09275f1d9f540.tar.gz
Exploding layer: sha256:6fd240c277673683f0b16a0d7903c036c307954976e19e2f82a6873327d1d69b.tar.gz
Exploding layer: sha256:bc8e89fc965b91eb7836a813e3301fd9df4dd1e8c0e58f2054dd2bee6d5c08f3.tar.gz
Exploding layer: sha256:77289c7b21c6f5fe4359bf4a807d45c4518cdd51803592264be73acd0b4e1a0a.tar.gz
Exploding layer: sha256:c5a9c84f47a262e213f35dce971d84403fdadfc458dcaae63d7bbc11e6af15fb.tar.gz
Exploding layer: sha256:7b845ecb69340b9ce7b5ba62c5c78058c892649e3bda3ccd26b4fee33d13597e.tar.gz
WARNING: Warning handling tar header: Hard-link target 'usr/lib/x86_64-linux-gnu/libgsl.so.0' does not exist.
```

For some reason targets of hard-links do not exist yet. We might be seeing an ordering problem here @vsoch ?

When the image finishes building, I'll report back whether the target path `/usr/lib/x86_64-linux-gnu/libgsl.so.0` exists.

**Comment by oesteban** [comment]
And this is what we get:

Singularity:
```
$ singularity exec mriqc-0.11.0.simg ls -lah /usr/lib/x86_64-linux-gnu/ | grep libgsl
-rw-r--r--  1 root root 2.3M Dec  7  2015 libgsl.so.19.0.0
lrwxrwxrwx  1 root root   20 Dec  7  2015 libgslcblas.so.0 -> libgslcblas.so.0.0.0
-rw-r--r--  1 root root 247K Dec  7  2015 libgslcblas.so.0.0.0
```

Docker:
```
ls -lah /usr/lib/x86_64-linux-gnu/ | grep libgsl
lrwxrwxrwx  2 root root   16 Dec  7  2015 libgsl.so.0 -> libgsl.so.19.0.0
lrwxrwxrwx  2 root root   16 Dec  7  2015 libgsl.so.19 -> libgsl.so.19.0.0
-rw-r--r--  1 root root 2.3M Dec  7  2015 libgsl.so.19.0.0
lrwxrwxrwx  1 root root   20 Dec  7  2015 libgslcblas.so.0 -> libgslcblas.so.0.0.0
-rw-r--r--  1 root root 247K Dec  7  2015 libgslcblas.so.0.0.0
```

So, apparently, singularity is hard-linking while docker has a softlink.

**Comment by justbennet** [comment]
I get this

```
[bennet@flux-build tmp]$ singularity build mriqc-0.11.0.simg docker://poldracklab/mriqc:0.11.0
Docker image path: index.docker.io/poldracklab/mriqc:0.11.0
Cache folder set to /home/bennet/.singularity/docker
[25/25] |===================================| 100.0% 
Importing: base Singularity environment
Exploding layer: sha256:c832082614738021cf51d68e84457a45a3f85dbe0ddbb93000c5dc5aae77fe93.tar.gz
Exploding layer: sha256:6e1a85c1d66a18674bdb5cee0a7d6b294aa4f1921d3a13074004d00485868051.tar.gz
Exploding layer: sha256:f1320ef45e201689247f36b8e037ed8de21532f952be224586cb96b43a495f36.tar.gz
Exploding layer: sha256:5a6ab6e6fbf62623bce0db5c75f3775f287c7b86cd0152b01ab09275f1d9f540.tar.gz
Exploding layer: sha256:6fd240c277673683f0b16a0d7903c036c307954976e19e2f82a6873327d1d69b.tar.gz
Exploding layer: sha256:bc8e89fc965b91eb7836a813e3301fd9df4dd1e8c0e58f2054dd2bee6d5c08f3.tar.gz
Exploding layer: sha256:77289c7b21c6f5fe4359bf4a807d45c4518cdd51803592264be73acd0b4e1a0a.tar.gz
Exploding layer: sha256:c5a9c84f47a262e213f35dce971d84403fdadfc458dcaae63d7bbc11e6af15fb.tar.gz
WARNING: Warning reading tar header: Ignoring malformed pax extended attribute
WARNING: Warning reading tar header: Ignoring malformed pax extended attribute
Exploding layer: sha256:7b845ecb69340b9ce7b5ba62c5c78058c892649e3bda3ccd26b4fee33d13597e.tar.gz
WARNING: Warning handling tar header: Can't create 'usr/lib/x86_64-linux-gnu/libgsl.so.19'
```

and looking in the tar file referred to, it does show that the symlink is being created prior to the file to which the link points exists.

```
$ tar tzvf 7b845ecb69340b9ce7b5ba62c5c78058c892649e3bda3ccd26b4fee33d13597e.tar.gz | grep -B2 -A2 libgsl

lrwxrwxrwx 0/0               0 2017-11-16 18:52 usr/lib/x86_64-linux-gnu/libdrm_radeon.so -> libdrm_radeon.so.1.0.1
lrwxrwxrwx 0/0               0 2018-01-29 15:07 usr/lib/x86_64-linux-gnu/libglapi.so -> libglapi.so.0.0.0
lrwxrwxrwx 0/0               0 2015-12-07 16:04 usr/lib/x86_64-linux-gnu/libgsl.so.0 -> libgsl.so.19.0.0
hrwxrwxrwx 0/0               0 2015-12-07 16:04 usr/lib/x86_64-linux-gnu/libgsl.so.19 link to usr/lib/x86_64-linux-gnu/libgsl.so.0
-rw-r--r-- 0/0         2352808 2015-12-07 16:04 usr/lib/x86_64-linux-gnu/libgsl.so.19.0.0
lrwxrwxrwx 0/0               0 2015-12-07 16:04 usr/lib/x86_64-linux-gnu/libgslcblas.so.0 -> libgslcblas.so.0.0.0
-rw-r--r-- 0/0          251936 2015-12-07 16:04 usr/lib/x86_64-linux-gnu/libgslcblas.so.0.0.0
lrwxrwxrwx 0/0               0 2015-08-17 19:48 usr/lib/x86_64-linux-gnu/libjpeg.so.62 -> libjpeg.so.62.0.0
-rw-r--r-- 0/0          150184 2015-08-17 19:48 usr/lib/x86_64-linux-gnu/libjpeg.so.62.0.0
```

but the regular `tar` provided by GNU seems to go ahead and create the sym links properly.  This is what results from running `tar xzvf` on the file Singularity downloaded.

```
[bennet@flux-build x86_64-linux-gnu]$ ls -l libgsl*
lrwxrwxrwx 1 bennet hpcstaff      20 Dec  7  2015 libgslcblas.so.0 -> libgslcblas.so.0.0.0
-rw-r--r-- 1 bennet hpcstaff  251936 Dec  7  2015 libgslcblas.so.0.0.0
lrwxrwxrwx 2 bennet hpcstaff      16 Dec  7  2015 libgsl.so.0 -> libgsl.so.19.0.0
lrwxrwxrwx 2 bennet hpcstaff      16 Dec  7  2015 libgsl.so.19 -> libgsl.so.19.0.0
-rw-r--r-- 1 bennet hpcstaff 2352808 Dec  7  2015 libgsl.so.19.0.0
```

@vsoch Maybe Singularity is using something else to unpack the archive, and it is imposing some overly scrupulous error checking?

**Comment by mattcieslak** [comment]
Thanks @justbennet I was able to get it to work with the following def:

```
Bootstrap: docker
From: poldracklab/mriqc:latest

%setup
apt-get install -y libopenblas-dev

%post

# Miniconda or Conda does not set permissions properly.  Make sure that
# everyone can read and execute what they should.
chmod -R a+rX /usr/local/miniconda

ln -s /usr/lib/x86_64-linux-gnu/libgsl.so.19.0.0 \
      /usr/lib/x86_64-linux-gnu/libgsl.so.19

ln -s /usr/lib/x86_64-linux-gnu/libgsl.so.19.0.0 \
      /usr/lib/x86_64-linux-gnu/libgsl.so.0

# Must make sure that the libGL.so.1 is in the right location for AFNI
if [ -e /usr/lib/x86_64-linux-gnu/libGL.so.1 ] ; then
    rm -f /usr/lib/x86_64-linux-gnu/libGL.so.1
fi
ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0 \
   /usr/lib/x86_64-linux-gnu/libGL.so.1
```

**Comment by vsoch** [comment]
The ordering issue would depend on the version of singularity - I'm not actively developing it so if this is a more recent version and you think there is an issue, I would open it --> https://www.github.com/singularityware/singularity/issues. I **do** know that different Docker registry versions might have different manifests (with a change in ordering) to throw a nail into the bag. Either way, I'm very glad that you have a recipe that has it working!

**Comment by oesteban** [comment]
I've checked and #733 seems to fix the issue for me.

@mattcieslak could I ask you to run:

```
$ singularity build pl-mriqc0.12.0-dev0.simg docker://poldracklab/mriqc:0.12.0-dev0
$ singularity exec pl-mriqc0.12.0-dev0.simg 3dSkullStrip
```

Thanks!

**Comment by mattcieslak** [comment]
Thanks @oesteban the new image works!
