### ISSUE TITLE
Installation of mriqc on python-3.4.3 CentOS 6.8

### ISSUE THREAD

**Issue by as7a5** [poldracklab/mriqc#658]
Hi All,
I am running to the following error. I apreciate any help:
pardoh01@node001:~/bids/abide$ mriqc leuven01 test_out/ participant --participant-label 0050697
Traceback (most recent call last):
  File "/local/apps/python/3.4.3/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.9.10+2.g547b2c9', 'console_scripts', 'mriqc')()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/mriqc-0.9.10+2.g547b2c9-py3.4.egg/mriqc/bin/mriqc_run.py", line 162, in main
    from ..workflows.core import build_workflow
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/mriqc-0.9.10+2.g547b2c9-py3.4.egg/mriqc/workflows/__init__.py", line 21, in <module>
    from .anatomical import anat_qc_workflow
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/mriqc-0.9.10+2.g547b2c9-py3.4.egg/mriqc/workflows/anatomical.py", line 50, in <module>
    from niworkflows.anat.skullstrip import afni_wf as skullstrip_wf
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/anat/__init__.py", line 7, in <module>
    from niworkflows.anat.mni import RobustMNINormalization
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/anat/mni.py", line 18, in <module>
    from niworkflows.interfaces.fixes import (
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/interfaces/__init__.py", line 6, in <module>
    from .registration import (FLIRTRPT as FLIRT,
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/interfaces/registration.py", line 22, in <module>
    from ..anat import mni
ImportError: cannot import name 'mni'
2017-10-30 16:35:32,716 interface:INFO Closing display (if virtual)

**Comment by oesteban** [comment]
Seems related to #655

Please update niworkflows:

```
pip install niworkflows --upgrade
```

That should be enough. Please, let us know if that fixed the issue.

**Comment by as7a5** [comment]
Already uptodate:

[root@node001 siavoa01]# module add local shared python/3.4.3
[root@node001 siavoa01]# pip install niworkflows --upgrade
Requirement already up-to-date: niworkflows in /local/apps/python/3.4.3/lib/python3.4/site-packages
Requirement already up-to-date: networkx>=1.9 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: sklearn in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: python-dateutil>=2.2 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: pandas in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: scipy>=0.14 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: click>=6.6.0 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: nibabel>=2.1.0 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: pydot>=1.2.3 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: numpy>=1.9.0 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: svgutils in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: traits>=4.6 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: jinja2 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: packaging in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: tinycss in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: future>=0.16.0 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: pytest>=3.0 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: mock in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: prov==1.5.0 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: pydotplus in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: funcsigs in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: simplejson>=3.8.0 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: nilearn>=0.2.6 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: matplotlib in /local/apps/python/3.4.3/lib/python3.4/site-packages (from niworkflows)
Requirement already up-to-date: decorator>=4.1.0 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from networkx>=1.9->niworkflows)
Requirement already up-to-date: scikit-learn in /local/apps/python/3.4.3/lib/python3.4/site-packages (from sklearn->niworkflows)
Requirement already up-to-date: six>=1.5 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from python-dateutil>=2.2->niworkflows)
Requirement already up-to-date: pytz>=2011k in /local/apps/python/3.4.3/lib/python3.4/site-packages (from pandas->niworkflows)
Requirement already up-to-date: pyparsing>=2.1.4 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from pydot>=1.2.3->niworkflows)
Requirement already up-to-date: lxml in /local/apps/python/3.4.3/lib/python3.4/site-packages (from svgutils->niworkflows)
Requirement already up-to-date: MarkupSafe>=0.23 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from jinja2->niworkflows)
Requirement already up-to-date: setuptools in /local/apps/python/3.4.3/lib/python3.4/site-packages (from pytest>=3.0->niworkflows)
Requirement already up-to-date: py>=1.4.33 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from pytest>=3.0->niworkflows)
Requirement already up-to-date: pbr>=0.11 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from mock->niworkflows)
Requirement already up-to-date: rdflib>=4.2.1 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from prov==1.5.0->niworkflows)
Requirement already up-to-date: cycler>=0.10 in /local/apps/python/3.4.3/lib/python3.4/site-packages (from matplotlib->niworkflows)
Requirement already up-to-date: isodate in /local/apps/python/3.4.3/lib/python3.4/site-packages (from rdflib>=4.2.1->prov==1.5.0->niworkflows)
[root@node001 siavoa01]#

**Comment by oesteban** [comment]
what does
```Bash
python -c "import niworkflows; print(niworkflows.__version__)"
```
says?

**Comment by as7a5** [comment]
[root@node001 siavoa01]# python -c "import niworkflows; print(niworkflows.__version__)"
0.1.8

Also this is python-3.4.3

**Comment by as7a5** [comment]
[root@node001 ~]# module add local shared python/3.4.3
[root@node001 ~]# python -c "import niworkflows; print(niworkflows.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
[root@node001 ~]#

**Comment by oesteban** [comment]
Ok, let's try to update niworkflows to the latest version:

```
pip install git+https://github.com/poldracklab/niworkflows.git --upgrade
```

That should fix this error.

**Comment by as7a5** [comment]
Hi Oscar,
I think we are getting closer:

[root@node001 abide]# mriqc leuven01 test_out/ participant --participant-label 0050697
2017-11-01 10:15:05,197 interface:WARNING afni executable not found.
2017-11-01 10:15:05,198 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2017-11-01 10:15:05,206 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2017-11-01 10:15:05,207 niworkflows:INFO Dataset created in /root/.cache/stanford-crn/mni_icbm152_nlin_asym_09c
2017-11-01 10:15:05,208 niworkflows:INFO Downloading data from https://files.osf.io/v1/resources/fvuh8/providers/osfstorage//580705089ad5a101f17944a9 ...
Downloaded 162303251 of 162303251 bytes (100.0%,    0.0s remaining) ...done. (5 seconds, 0 min)
2017-11-01 10:15:11,955 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2017-11-01 10:15:12,211 mriqc.cli:WARNING No bold scans were found in /ifs/home/pardoh01/bids/abide/leuven01
2017-11-01 10:15:12,211 mriqc.cli:WARNING No T2w scans were found in /ifs/home/pardoh01/bids/abide/leuven01
2017-11-01 10:15:12,211 mriqc.cli:WARNING Anonymized quality metrics will be submitted to MRIQC's metrics repository. Use --no-sub to disable submission.
2017-11-01 10:15:16,769 workflow:ERROR Node inu_n4.a0 failed to run on host node001.
2017-11-01 10:15:16,770 workflow:ERROR Saving crash info to /ifs/home/pardoh01/bids/abide/test_out/logs/crash-20171101-101516-root-inu_n4.a0-147f4533-28c9-4557-999d-c62862cab622.txt
Traceback (most recent call last):
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/interfaces/ants/segmentation.py", line 392, in _run_interface
    runtime, correct_return_codes)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/interfaces/base.py", line 1647, in _run_interface
    (self.cmd.split()[0], runtime.hostname))
OSError: command 'N4BiasFieldCorrection' could not be found on host node001

2017-11-01 10:15:18,776 workflow:ERROR could not run node: workflow_enumerator.anatMRIQCT1w.AFNISkullStripWorkflow.inu_n4.a0
Traceback (most recent call last):
  File "/local/apps/python/3.4.3/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.9.10+2.g547b2c9', 'console_scripts', 'mriqc')()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/mriqc-0.9.10+2.g547b2c9-py3.4.egg/mriqc/bin/mriqc_run.py", line 315, in main
    workflow.run(**plugin_settings)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 590, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 189, in run
    report_nodes_not_run(notrun)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/tools.py", line 79, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
[root@node001 abide]#

**Comment by oesteban** [comment]
You're right. Now your issue it's unrelated to fMRIprep: you'll need to install ANTs, which provides N4BiasFieldCorrection.

More info here https://github.com/nipy/nipype/issues/2266#issuecomment-340851449

**Comment by as7a5** [comment]
Hi Again Oscar,
We are getting even closer. We have version 0.3.8.1 of ants installed as a module and I loaded it and now I got the following:
pardoh01@node001:~/bids/abide$ mriqc leuven01 test_out/ participant --participant-label 0050697
2017-11-02 12:03:02,051 interface:WARNING afni executable not found.
2017-11-02 12:03:02,052 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2017-11-02 12:03:02,060 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2017-11-02 12:03:02,203 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2017-11-02 12:03:02,530 mriqc.cli:WARNING No bold scans were found in /ifs/home/pardoh01/bids/abide/leuven01
2017-11-02 12:03:02,530 mriqc.cli:WARNING No T2w scans were found in /ifs/home/pardoh01/bids/abide/leuven01
2017-11-02 12:03:02,530 mriqc.cli:WARNING Anonymized quality metrics will be submitted to MRIQC's metrics repository. Use --no-sub to disable submission.
2017-11-02 12:03:07,697 workflow:ERROR Node inu_n4.a0 failed to run on host node001.
2017-11-02 12:03:07,697 workflow:ERROR Saving crash info to /ifs/home/pardoh01/bids/abide/test_out/logs/crash-20171102-120307-pardoh01-inu_n4.a0-17b8fd3f-8171-4f2a-b08d-5fdeffbd4579.txt
Traceback (most recent call last):
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 390, in run
    raise ex
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 378, in run
    rmtree(outdir)
  File "/local/apps/python/3.4.3/lib/python3.4/shutil.py", line 464, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/local/apps/python/3.4.3/lib/python3.4/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/local/apps/python/3.4.3/lib/python3.4/shutil.py", line 420, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'result_inu_n4.pklz'

2017-11-02 12:03:09,709 workflow:ERROR could not run node: workflow_enumerator.anatMRIQCT1w.AFNISkullStripWorkflow.inu_n4.a0
Traceback (most recent call last):
  File "/local/apps/python/3.4.3/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.9.10+2.g547b2c9', 'console_scripts', 'mriqc')()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/mriqc-0.9.10+2.g547b2c9-py3.4.egg/mriqc/bin/mriqc_run.py", line 315, in main
    workflow.run(**plugin_settings)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 590, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 189, in run
    report_nodes_not_run(notrun)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/tools.py", line 79, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
pardoh01@node001:~/bids/abide$

**Comment by as7a5** [comment]
That was as a user. As root I get the following. Still better:
[root@node001 abide]# mriqc leuven01 test_out/ participant --participant-label 0050697
2017-11-02 12:08:23,462 interface:WARNING afni executable not found.
2017-11-02 12:08:23,463 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2017-11-02 12:08:23,471 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2017-11-02 12:08:23,485 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2017-11-02 12:08:23,740 mriqc.cli:WARNING No bold scans were found in /ifs/home/pardoh01/bids/abide/leuven01
2017-11-02 12:08:23,740 mriqc.cli:WARNING No T2w scans were found in /ifs/home/pardoh01/bids/abide/leuven01
2017-11-02 12:08:23,740 mriqc.cli:WARNING Anonymized quality metrics will be submitted to MRIQC's metrics repository. Use --no-sub to disable submission.
2017-11-02 12:09:44,493 workflow:ERROR Node fsl_bet.a0 failed to run on host node001.
2017-11-02 12:09:44,495 workflow:ERROR Saving crash info to /ifs/home/pardoh01/bids/abide/test_out/logs/crash-20171102-120944-root-fsl_bet.a0-1a89ba56-5d3f-4e58-bb28-c161eb8f032d.txt
Traceback (most recent call last):
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/interfaces/fsl/preprocess.py", line 144, in _run_interface
    runtime = super(BET, self)._run_interface(runtime)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/interfaces/base.py", line 1647, in _run_interface
    (self.cmd.split()[0], runtime.hostname))
OSError: command 'bet' could not be found on host node001

2017-11-02 12:09:44,499 workflow:ERROR Node skullstrip.a0 failed to run on host node001.
2017-11-02 12:09:44,499 workflow:ERROR Saving crash info to /ifs/home/pardoh01/bids/abide/test_out/logs/crash-20171102-120944-root-skullstrip.a0-5fe15e0b-9abc-4321-a262-45bed3defac2.txt
Traceback (most recent call last):
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/interfaces/afni/base.py", line 129, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/interfaces/base.py", line 1647, in _run_interface
    (self.cmd.split()[0], runtime.hostname))
OSError: command '3dSkullStrip' could not be found on host node001

2017-11-02 12:09:46,553 workflow:ERROR could not run node: workflow_enumerator.anatMRIQCT1w.HeadMaskWorkflow.fsl_bet.a0
2017-11-02 12:09:46,553 workflow:ERROR could not run node: workflow_enumerator.anatMRIQCT1w.AFNISkullStripWorkflow.skullstrip.a0
Traceback (most recent call last):
  File "/local/apps/python/3.4.3/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.9.10+2.g547b2c9', 'console_scripts', 'mriqc')()
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/mriqc-0.9.10+2.g547b2c9-py3.4.egg/mriqc/bin/mriqc_run.py", line 315, in main
    workflow.run(**plugin_settings)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 590, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 189, in run
    report_nodes_not_run(notrun)
  File "/local/apps/python/3.4.3/lib/python3.4/site-packages/niworkflows/nipype/pipeline/plugins/tools.py", line 79, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

**Comment by oesteban** [comment]
Easier first: as root you can see that your system lacks of `bet` and `3dSkullStrip`. Those are binaries provided by FSL and AFNI (respectively). You would need to install both.

Alternatively, you could consider container solutions (docker or singularity).

As a user, it seems a plain permissions issue. You may have run mriqc as root previously and the permissions stayed that way.

**Comment by lrq3000** [comment]
Yes I can confirm I just had the same issue again, just had to install github version of mriqc and niworkflows, now everything work again!

**Comment by as7a5** [comment]
Thanks a lot Oscar. It seems its all good.

**Comment by oesteban** [comment]
Thanks a lot, please feel free to reopen if needed.
