### ISSUE TITLE
RuntimeError: structure and input must have same dimensionality(ds000210)

### ISSUE THREAD

**Issue by suyashdb** [poldracklab/mriqc#660]
For ds210 most of the logs and error are for task runs(which are multiecho). I guess that is ok however, there are certain errors for T1w as follows:

```
Node: workflow_enumerator.anatMRIQCT1w.AirMaskWorkflow.RotationMask
Working directory: /usr/local/src/mriqc/work/workflow_enumerator/anatMRIQCT1w/AirMaskWorkflow/_in_file_..snapshot..data..sub-07..anat..sub-07_T1w.nii.gz/RotationMask

Node inputs:

ignore_exception = False
in_file = /usr/local/src/mriqc/work/workflow_enumerator/anatMRIQCT1w/_in_file_..snapshot..data..sub-07..anat..sub-07_T1w.nii.gz/conform/sub-07_T1w_conformed.nii.gz

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1086, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/anatomical.py", line 367, in _run_interface
    mask = nd.binary_opening(mask, structure=struc).astype(
  File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 606, in binary_opening
    origin)
  File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 378, in binary_erosion
    output, border_value, origin, 0, brute_force)
  File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 228, in _binary_erosion
    raise RuntimeError('structure and input must have same dimensionality')
RuntimeError: structure and input must have same dimensionality
```

**Comment by oesteban** [comment]
For the record: T1w images in ds000210 have a 4th dimension of size 1 for only some subjects:

```
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-01/anat/sub-01_T1w.nii.gz  int16  [256, 256, 176]      1.00x1.00x1.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-02/anat/sub-02_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-03/anat/sub-03_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-04/anat/sub-04_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-05/anat/sub-05_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-06/anat/sub-06_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-07/anat/sub-07_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-08/anat/sub-08_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-09/anat/sub-09_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-10/anat/sub-10_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-11/anat/sub-11_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-12/anat/sub-12_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-13/anat/sub-13_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-14/anat/sub-14_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-15/anat/sub-15_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-16/anat/sub-16_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-17/anat/sub-17_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-18/anat/sub-18_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-19/anat/sub-19_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-20/anat/sub-20_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-21/anat/sub-21_T1w.nii.gz  int16  [256, 256, 176]      1.00x1.00x1.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-22/anat/sub-22_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-23/anat/sub-23_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-24/anat/sub-24_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-25/anat/sub-25_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-26/anat/sub-26_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-27/anat/sub-27_T1w.nii.gz float32 [256, 256, 176]      1.00x1.00x1.00       #exts: 1
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-28/anat/sub-28_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-29/anat/sub-29_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-30/anat/sub-30_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
/oak/stanford/groups/russpold/data/openfmri/ds000210/sub-31/anat/sub-31_T1w.nii.gz float64 [256, 256, 176,   1] 1.00x1.00x1.00x0.00
```
