### ISSUE TITLE
mriqc bare metal install - skullstrip fails

### ISSUE THREAD

**Issue by isLitt** [poldracklab/mriqc#672]
I have a bare metal install of mriqc. I do not think there is an issue related to any of the pre req packages as the checks for those packages run fine. The error I always get is related skullstrip failing to run on the host.

2017-12-08 10:30:52,391 workflow:WARNING [Node] Exception "workflow_enumerator.anatMRIQCT1w.AFNISkullStripWorkflow.skullstrip" (/gpfs/group/sjw42/default/freesurfer_subjects/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..gpfs..group..sjw42..default..freesurfer_subjects..ds001..sub-16..anat..sub-16_T1w.nii.gz/skullstrip)
2017-12-08 10:30:54,054 workflow:ERROR Node skullstrip.a15 failed to run on host comp-ic-0016.aci.ics.psu.edu.
2017-12-08 10:30:54,054 workflow:ERROR Saving crash info to /gpfs/group/sjw42/default/freesurfer_subjects/out/logs/crash-20171208-103054-vus133-skullstrip.a15-2e72625e-1de4-432d-aac5-50799a29a0d1.txt

I'm not sure what the cause could be. Please let me know if you require any additional information. I'm running python 3.6, and the latest versions of all the packages specified on the bare metal install page.

Thank you.

**Comment by chrisfilo** [comment]
Could you share the content of /gpfs/group/sjw42/default/freesurfer_subjects/out/logs/crash-20171208-103054-vus133-skullstrip.a15-2e72625e-1de4-432d-aac5-50799a29a0d1.txt ?

**Comment by isLitt** [comment]
Hi chrisfilo,

The content is: 

Node: workflow_enumerator.anatMRIQCT1w.AFNISkullStripWorkflow.skullstrip
Working directory: /gpfs/group/sjw42/default/freesurfer_subjects/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..gpfs..group..sjw42..default..freesurfer_subjects..ds001..sub-16..anat..sub-16_T1w.nii.gz/skullstrip

Node inputs:

args = <undefined>
environ = {}
ignore_exception = False
in_file = /gpfs/group/sjw42/default/freesurfer_subjects/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..gpfs..group..sjw42..default..freesurfer_subjects..ds001..sub-16..anat..sub-16_T1w.nii.gz/inu_n4/sub-16_T1w_conformed_corrected.nii.gz
num_threads = 1
out_file = <undefined>
outputtype = NIFTI_GZ
terminal_output = <undefined>

Traceback (most recent call last):
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 62, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 404, in run
    self._run_interface(execute=True)
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    return self._run_command(execute)
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 639, in _run_command
    result = self._interface.run()
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 459, in run
    env['DISPLAY'] = config.get_display()
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/utils/config.py", line 286, in get_display
    ndisp = int(sysdisplay.split(':')[-1])
ValueError: invalid literal for int() with base 10: '1000.0'

**Comment by chrisfilo** [comment]
Thanks. What is the DISPLAY environment variable set to in the Shell you
are running mriqc from?

Best,
Chris

**Comment by isLitt** [comment]
Hi Chris,
It is 146.186.1.116:1000.0

Could that be the issue?

**Comment by chrisfilo** [comment]
Yes - could you try unsetting it?

Best,
Chris

**Comment by isLitt** [comment]
Hi Chris,

When I do that I get a bunch of errors that look like this with different skullstrip node numbers.

2017-12-08 11:30:38,780 workflow:ERROR Node skullstrip.a15 failed to run on host comp-ic-0016.aci.ics.psu.edu.
2017-12-08 11:30:38,781 workflow:ERROR Saving crash info to /gpfs/group/sjw42/default/freesurfer_subjects/out/logs/crash-20171208-113038-vus133-skullstrip.a15-8de98503-220b-4831-bd48-706cba4c988b.txt
Traceback (most recent call last):
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 62, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 404, in run
    self._run_interface(execute=True)
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    return self._run_command(execute)
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 639, in _run_command
    result = self._interface.run()
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 459, in run
    env['DISPLAY'] = config.get_display()
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/utils/config.py", line 309, in get_display
    self._display = Xvfb(nolisten='tcp')
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/xvfbwrapper.py", line 41, in __init__
    raise EnvironmentError(msg)
OSError: Can not find Xvfb. Please install it and try again.

**Comment by isLitt** [comment]
This is the crash log output:

Node: workflow_enumerator.anatMRIQCT1w.AFNISkullStripWorkflow.skullstrip
Working directory: /gpfs/group/sjw42/default/freesurfer_subjects/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..gpfs..group..sjw42..default..freesurfer_subjects..ds001..sub-16..anat..sub-16_T1w.nii.gz/skullstrip

Node inputs:

args = <undefined>
environ = {}
ignore_exception = False
in_file = /gpfs/group/sjw42/default/freesurfer_subjects/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..gpfs..group..sjw42..default..freesurfer_subjects..ds001..sub-16..anat..sub-16_T1w.nii.gz/inu_n4/sub-16_T1w_conformed_corrected.nii.gz
num_threads = 1
out_file = <undefined>
outputtype = NIFTI_GZ
terminal_output = <undefined>

Traceback (most recent call last):
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 62, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 404, in run
    self._run_interface(execute=True)
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    return self._run_command(execute)
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 639, in _run_command
    result = self._interface.run()
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 459, in run
    env['DISPLAY'] = config.get_display()
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/niworkflows/nipype/utils/config.py", line 309, in get_display
    self._display = Xvfb(nolisten='tcp')
  File "/gpfs/group/sjw42/default/sjw42_collab/sw/Python-3.6.3/build/lib/python3.6/site-packages/xvfbwrapper.py", line 41, in __init__
    raise EnvironmentError(msg)
OSError: Can not find Xvfb. Please install it and try again.

**Comment by chrisfilo** [comment]
You would need to install Xvfb for this to work. Alternatively you can try
setting DISPLAY to "146.186.1.116:1000".

To avoid all such headache I really recommend using Singularity or Docker.

Best,
Chris

**Comment by isLitt** [comment]
Hi Chris,

Setting DISPLAY to "146.186.1.116:1000" seems to have fixed the problem.

Thank you very much!
