### ISSUE TITLE
AnatQC fails for a subset of subjects

### ISSUE THREAD

**Issue by mfalkiewicz** [poldracklab/mriqc#677]
I tried to run anatomical QC on ~1500 subjects using SLURM + singularity (mriqc 0.10). It completed successfully for ~1300 subjects and failed for the remaining ones. All failed subjects had the same error: 

> mfalkiewicz@brainb32a:~/largefs/singularity/data_processing/SCZ/QC/out/logs$ cat crash-20180114-165639-mfalkiewicz-smoothness.a0-090c69ed-fc34-4f22-8b9b-5721ea6eacce.txt
Node: workflow_enumerator.anatMRIQCT1w.ComputeIQMs.smoothness
Working directory: /work/workflow_enumerator/anatMRIQCT1w/ComputeIQMs/_in_file_..data..sub-00069..anat..sub-00069_T1w.nii.gz/smoothness

> Node inputs:

> acf = True
args = -ShowMeClassicFWHM
arith = <undefined>
automask = False
combine = True
compat = <undefined>
demed = <undefined>
detrend = True
environ = {}
geom = <undefined>
ignore_exception = False
in_file = /work/workflow_enumerator/anatMRIQCT1w/_in_file_..data..sub-00069..anat..sub-00069_T1w.nii.gz/conform/sub-00069_T1w_conformed.nii.gz
mask = /work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-00069..anat..sub-00069_T1w.nii.gz/binarize/sub-00069_T1w_conformed_calc_thresh.nii.gz
out_detrend = <undefined>
out_file = <undefined>
out_subbricks = <undefined>
terminal_output = <undefined>
unif = <undefined>

> Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1089, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1176, in aggregate_outputs
    raise error
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1170, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/traits_extension.py", line 92, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'out_acf' of a FWHMxOutputSpec instance is an existing file name, but the path  '/work/workflow_enumerator/anatMRIQCT1w/ComputeIQMs/_in_file_..data..sub-00069..anat..sub-00069_T1w.nii.gz/smoothness/3dFWHMx.1D' does not exist.

Indeed, the indicated file does not exist for the subjects with this error:

> mfalkiewicz@brainb32a:~/largefs/singularity/data_processing/SCZ/QC/work/workflow_enumerator/anatMRIQCT1w/ComputeIQMs/_in_file_..data..sub-00069..anat..sub-00069_T1w.nii.gz/smoothness$ ls
_inputs.pklz  _node.pklz  _report  command.txt  result_smoothness.pklz  sub-00069_T1w_conformed_fwhmx.out  sub-00069_T1w_conformed_subbricks.out

However, the bizarre thing happens for the subjects that completed successfully. They also do not have the 3dFWHMx.1D file. Nor any output files that were present in the failed subjects:

> mfalkiewicz@brainb32a:~/largefs/singularity/data_processing/SCZ/QC/work/workflow_enumerator/anatMRIQCT1w/ComputeIQMs/_in_file_..data..sub-00068..anat..sub-00068_T1w.nii.gz/smoothness$ ls
_0x20fa00ce42911f2b7d7c439fe86fca52.json  _inputs.pklz  _node.pklz  _report  command.txt  result_smoothness.pklz

All other failed and completed subject follow the same pattern. Any idea what might be going on?

**Comment by mfalkiewicz** [comment]
Further investigation yielded the following results:

> 2018-01-14 21:40:40,511 interface:INFO stderr 2018-01-14T21:40:40.510967:++ 3dFWHMx: AFNI version=AFNI_17.3.03 (Nov  9 2017) [64-bit]
2018-01-14 21:40:40,512 interface:INFO stderr 2018-01-14T21:40:40.512283:++ Authored by: The Bob
2018-01-14 21:40:40,516 interface:INFO stderr 2018-01-14T21:40:40.516693:*+ WARNING: Using the 'Classic' Gaussian FWHM is not recommended :(
2018-01-14 21:40:40,516 interface:INFO stderr 2018-01-14T21:40:40.516693: +  The '-acf' method gives a FWHM estimate which is more robust;
2018-01-14 21:40:40,516 interface:INFO stderr 2018-01-14T21:40:40.516693: +  however, assuming the spatial correlation of FMRI noise has
2018-01-14 21:40:40,516 interface:INFO stderr 2018-01-14T21:40:40.516693: +  a Gaussian shape is not a good model.
2018-01-14 21:40:40,713 interface:INFO stderr 2018-01-14T21:40:40.713507:++ Number of voxels in mask = 1983325
2018-01-14 21:40:40,885 interface:INFO stderr 2018-01-14T21:40:40.885552:*+ WARNING: -demed and/or -corder and/or -unif ignored: only 1 input sub-bricks
2018-01-14 21:40:40,885 interface:INFO stderr 2018-01-14T21:40:40.885552:++ start Classic FWHM calculations
2018-01-14 21:40:40,988 interface:INFO stderr 2018-01-14T21:40:40.987932: + Classic FWHM done (0.00 CPU s thus far)
2018-01-14 21:40:40,988 interface:INFO stderr 2018-01-14T21:40:40.987932:++ start ACF calculations out to radius = 14.71 mm
**2018-01-14 21:40:50,398 interface:INFO stderr 2018-01-14T21:40:50.398210:** ERROR: largest ACF found is 0.518093 -- too big for model fit!**
2018-01-14 21:40:50,398 interface:INFO stderr 2018-01-14T21:40:50.398210: + ACF done (0.00 CPU s thus far)
2018-01-14 21:40:50,415 workflow:DEBUG saved results in /work/workflow_enumerator/anatMRIQCT1w/ComputeIQMs/_in_file_..data..sub-00069..anat..sub-00069_T1w.nii.gz/smoothness/result_smoothness.pklz
2018-01-14 21:40:50,415 workflow:ERROR Node smoothness.a0 failed to run on host brainb24c.
2018-01-14 21:40:50,419 workflow:ERROR Saving crash info to /out/logs/crash-20180114-214050-mfalkiewicz-smoothness.a0-3966d7cf-6572-4914-91c9-3fc9c00b5b1d.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1089, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1176, in aggregate_outputs
    raise error
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1170, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/traits_extension.py", line 92, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'out_acf' of a FWHMxOutputSpec instance is an existing file name, but the path  '/work/workflow_enumerator/anatMRIQCT1w/ComputeIQMs/_in_file_..data..sub-00069..anat..sub-00069_T1w.nii.gz/smoothness/3dFWHMx.1D' does not exist.

Thus, it seems that this is the problem with estimating ACF using 3dFWHMx. Any ideas how to address this issue?

**Comment by chrisfilo** [comment]
I've seen this recently on another dataset, so we should definitely address this. It has been introduced when we updated AFNi recently. The ironic thing is that we don't even use ACF - just the old smoothness implementation.

Could you clarify which mask is more liberal 'auto' or mriqc?

**Comment by mfalkiewicz** [comment]
@chrisfilo I examined a single dataset and 'auto' was more liberal -- it included the brain, as well as a large portion of the head. I tried to fixed the issue by removing all masking. However, it broke other subset of subjects! I will try the solution with the automask option on. 

However, another odd part of the issue is that even when 3dFWHMx ACF fails, it outputs the classic FWHM:

> ++ start ACF calculations out to radius = 14.71 mm
** ERROR: largest ACF found is 0.518093 -- too big for model fit!
 + ACF done (0.00 CPU s thus far)
 4.83634  4.98931  4.89285     4.90576
 -1  -1  -1     -1

So it's dumped into the terminal, but it's not dumped into the 1D file. Maybe reading this directly from stdout would be a solution for this problem? It's essentially the second to last line of stdout.

**Comment by chrisfilo** [comment]
It worked on the two cases that failed for me before.

Best,
Chris

**Comment by mfalkiewicz** [comment]
@chrisfilo It did not work for approximately 500/1500 subjects in my dataset. 

There is an interesting quote in the 3dFWHMx documentation:

> IF YOUR DATA HAS SMOOTH-ISH SPATIAL STRUCTURE YOU CAN'T GET RID OF:
For example, you only have 1 volume, say from PET imaging.  In this case,
the standard estimate of the noise smoothness will be mixed in with the
structure of the background.  An approximate way to avoid this problem
is provided with the semi-secret '-2difMAD' option, which uses a combination of
first-neighbor and second-neighbor differences to estimate the smoothness,
rather than just first-neighbor differences, and uses the MAD of the differences
rather than the standard deviation.  (If you must know the details, read the
source code in mri_fwhm.c!)                    [For Jatin Vaidya, March 2010]

I tested this option, it dumps the FWHM estimates into the stdout without an error. This could be the solution to the problem...

**Comment by chrisfilo** [comment]
So the failure rate with automask is larger than with mask calculated by MRIQC?

**Comment by mfalkiewicz** [comment]
Yes, it is.

**Comment by chrisfilo** [comment]
Ok - I got a fix but it involves nipype (see above).

**Comment by mfalkiewicz** [comment]
The current combination of fixes should do. I guess in this scenario the nipype fix is not needed. If you won't pass -acf to 3dFWHMx it will be calculated and output to stdout anyway, but nipype is not going to expect the 1D file. The nipype fix should allow to use estimates based on "-2difMAD" option passed to the function.

I can confirm that mriqc does not produce crash files anymore after including these fixes. However, I would consider including the -2difMAD option as the default for FWHM calculation.

**Comment by chrisfilo** [comment]
ACF values are currently not used by MRIQC - only the old smoothness estimates. Even if we were to add support for ACF I would have to investigate the interpretability of values calculated with the "-2difMAD" option.
