### ISSUE TITLE
MRIQC on T1w images error

### ISSUE THREAD

**Issue by n2parker** [poldracklab/mriqc#681]
Hello,
I have downloaded mriqc on a server using python3 with the work-around provided here https://github.com/poldracklab/mriqc/issues/470.
The server does not have docker so the python installation was necessary.
There are roughly 400 T1w MRI scans (nifty, .nii.gz) and structured in BIDS format.
When I try to run "mriqc bids-root/ bids-outfolder/ participant" I get the following error: 
TypeError: not enough arguments for format string.
Am I missing additional tags or commands? or is there some other issue?

**Comment by chrisfilo** [comment]
Could you provide full console output (in addition to just the error line)?

**Comment by n2parker** [comment]
Hi,
here is the full read out:

(mriqc) (Python3_env) [nparker@gpc-f102n084-ib0 nparker]$ mriqc /scratch/t/tpaus/nparker/Brazil_Wave2_Jan312016/Brazil_Wav2/All_Participants_Brazil_wave2/mri /scratch/t/tpaus/nparker/MRIQC/Brazil_Wave2_QC participant
   /home/t/tpaus/nparker/.conda/envs/mriqc/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
   from ._conv import register_converters as _register_converters
   2018-01-22 11:09:20,033 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
   2018-01-22 11:09:20,288 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
   2018-01-22 11:09:20,329 interface:WARNING FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
   Traceback (most recent call last):
     File "/home/t/tpaus/nparker/.conda/envs/mriqc/bin/mriqc", line 11, in <module>
     load_entry_point('mriqc==0.10.1', 'console_scripts', 'mriqc')()
   File "/home/t/tpaus/nparker/.conda/envs/mriqc/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 301, in main
   wf_list.append(build_workflow(dataset[mod], mod, settings=settings))
   File "/home/t/tpaus/nparker/.conda/envs/mriqc/lib/python3.6/site-packages/mriqc/workflows/core.py", line 25, in build_workflow
   workflow = anat_qc_workflow(dataset, mod='T1w', settings=settings)
   File "/home/t/tpaus/nparker/.conda/envs/mriqc/lib/python3.6/site-packages/mriqc/workflows/anatomical.py", line 104, in anat_qc_workflow
   iqmswf = compute_iqms(settings, modality=mod)
   File "/home/t/tpaus/nparker/.conda/envs/mriqc/lib/python3.6/site-packages/mriqc/workflows/anatomical.py", line 245, in compute_iqms
   fwhm_interface = get_fwhmx()
   File "/home/t/tpaus/nparker/.conda/envs/mriqc/lib/python3.6/site-packages/mriqc/workflows/utils.py", line 169, in get_fwhmx
   afni_version = StrictVersion('%s.%s.%s' % afni.Info.version())
   TypeError: not enough arguments for format string

**Comment by n2parker** [comment]
Our server has Singularity however, I have never used this before. What are the steps to install the MRIQC container using Singularity? 
How do the commands to run the program differ from Docker?

**Comment by chrisfilo** [comment]
Steps are similar to FMRIPREP. See http://fmriprep.readthedocs.io/en/latest/installation.html#singularity-container

**Comment by oesteban** [comment]
Hi @n2parker, did you finally solve this problem?

**Comment by n2parker** [comment]
Hi,
yes this issue has been solved and I've successfully installed MRIQC. 
Thank you.
