### ISSUE TITLE
MRIQC T1w classifier (longitudinal)

### ISSUE THREAD

**Issue by araikes** [poldracklab/mriqc#711]
Hi all,
I was trying out the classifier on my longitudinal dataset (two sessions, ses-Pre and ses-Post). I'm using MRIQC 0.10.3.

I'm running the classifier through docker and using SLURM on a private cluster so that I can run multiple parallel studies with the same script. All I'm doing is assigning the classifier to a single process on the cluster. I've used used essentially the same syntax to run MRIQC in parallel for my subjects as well as the call for the group-level summary without issue. My call to the classifier is: 

``	sbatch -o $LOGS/MRIQC_classifier_out.txt \
	-e $LOGS/MRIQC_classifer_error.txt \
	--partition="long.q" \
	--job-name="MRIQC_classifier" \
	--wrap "docker run -i \
	-v $QCDIR:/scratch \
	-w /scratch \
	--entrypoint=/usr/local/miniconda/bin/mriqc_clf \
	poldracklab/mriqc \
	--train \
	--test \
	-X T1w.csv \
	--log-file \
	--nested_cv_kfold \
	--cv kfold \
	-v \
	--debug" 
``
where $QCDIR is my output directory from MRIQC and T1w.csv is the group-level IQM spreadsheet.

When I run that, I get the following error:

```
 Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc_clf", line 11, in <module>
    load_entry_point('mriqc==0.10.3', 'console_scripts', 'mriqc_clf')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_clf.py", line 201, in main
    thres=opts.threshold)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/classifier/helper.py", line 519, in predict_dataset
    prob_y, pred_y = self.predict(_xeval[columns])
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/classifier/helper.py", line 489, in predict
    proba = np.array(self._estimator.predict_proba(X))
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 115, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/pipeline.py", line 356, in predict_proba
    Xt = transform.transform(Xt)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/classifier/sklearn/preprocessing.py", line 215, in transform
    new_x[new_x.columns[self.ftmask_]], y)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/classifier/sklearn/preprocessing.py", line 166, in transform
    X.ix[:, colmask])
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/base.py", line 517, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 1046, in fit
    X = self._check_array(X, self.copy)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 1026, in _check_array
    estimator=self, dtype=FLOAT_DTYPES)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 433, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: could not convert string to float: 'Pre'
```

Is there a way to get the classifier to run on this dataset with this command set or do I need to do something different?

Thanks

**Comment by oesteban** [comment]
At a first look it seems there's a problem reading the T1w.csv file. Could you share that one with me (eg. over email)?

**Comment by araikes** [comment]
Sent it to you @oesteban
