### ISSUE TITLE
mriqc, Error, need help

### ISSUE THREAD

**Issue by desserdmi** [poldracklab/mriqc#723]
Dear all,

I have validated my dataset with bids validator: http://incf.github.io/bids-validator/ (No errors accured)

and I am trying to analyse the data quality with mriqc. I receive the following Error:

Dmitriys-MacBook-Pro:~ dmitriydesser$ docker run -it --rm -v /Users/dmitriydesser/Desktop/studie/bids:/data:ro -v /Users/dmitriydesser/Desktop/studie/mriqc:/out poldracklab/mriqc:latest /data /out participant --participant_label 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20

2018-06-27 22:55:10,697 mriqc.cli:WARNING No T2w scans were found in /data

2018-06-27 22:55:10,698 mriqc.cli:WARNING Anonymized quality metrics will be submitted to MRIQC's metrics repository. Use --no-sub to disable submission.

2018-06-27 22:55:24,453 workflow:WARNING Some nodes exceed the total amount of memory available (1.76GB).

Traceback (most recent call last):

  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>

    load_entry_point('mriqc==0.11.0', 'console_scripts', 'mriqc')()

  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 316, in main

    workflow.run(**plugin_settings)

  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run

    runner.run(execgraph, updatehash=updatehash, config=self.config)

  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 121, in run

    self._prerun_check(graph)

  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 211, in _prerun_check

    raise RuntimeError('Insufficient resources available for job')

RuntimeError: Insufficient resources available for job

Can anybody help me?

Thanks a lot!

Best,

Dima

**Comment by jdkent** [comment]
Hi Dima!

Thanks for the details, I think with what you've provided, I can slim down what the issue _should_ be. It appears docker only has access to 2 gb of RAM, whereas mriqc typically takes 8 gb of RAM, so you can [provision docker to have access to 8 gb of RAM](https://docs.docker.com/docker-for-mac/#advanced) if your machine has at least 10 gb of RAM (gotta give the operating system 2 gb to complete necessary tasks). If your machine does not have that much RAM, I can suggest trying to use the `--mem_gb <however much RAM you can spare>` option when calling mriqc, and limiting your call to one participant label to minimize memory consumption.

**Comment by desserdmi** [comment]
Thank you very much! It works! There are some Errors while preprocessing
step, but reports seem to be normal at the end.
 Thanks a lot for your help!

Best,

Dima


James Kent <notifications@github.com> schrieb am Do. 28. Juni 2018 um 04:57:

**Comment by jdkent** [comment]
Awesome! If you want to detail your preprocessing errors, [neurostars](https://neurostars.org/) would be the best place to get answers.

**Comment by oesteban** [comment]
Please reopen if you keep experiencing issues.
