### ISSUE TITLE
workflow issue

### ISSUE THREAD

**Issue by Irisfee** [poldracklab/mriqc#752]
Hi mriqc devs,

I am a newbie to fmri analysis and mriqc. I am running mriqc with docker and it crashed when dealing with T1w images. I am working on Mac OS 10.13.3. I am using MPRAGE dis3d/dis2d instead of ND files.

I used the following codes to run:
docker run -it --rm -v <bids_dir>:/data:ro -v <output_dir>:/out poldracklab/mriqc:latest /data /out participant

Here is the error log: 
Node: workflow_enumerator.anatMRIQCT1w.SpatialNormalization.SpatialNormalization
Working directory: /tmp/work/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..data..sub-001..ses-1..anat..sub-001_ses-1_acq-crop_T1w.nii/SpatialNormalization

Node inputs:

compress_report = auto
explicit_masking = True
flavor = fast
float = False
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1
moving_image = /tmp/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-001..ses-1..anat..sub-001_ses-1_acq-crop_T1w.nii/inu_n4/sub-001_ses-1_acq-crop_T1w_conformed_corrected.nii
moving_mask = /tmp/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-001..ses-1..anat..sub-001_ses-1_acq-crop_T1w.nii/binarize/sub-001_ses-1_acq-crop_T1w_conformed_calc_thresh.nii.gz
num_threads = 1
orientation = RAS
out_report = report.svg
reference = T1
reference_image = <undefined>
reference_mask = /niworkflows_data/mni_icbm152_nlin_asym_09c/2mm_brainmask.nii.gz
settings = <undefined>
template = mni_icbm152_nlin_asym_09c
template_resolution = 2

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/mni.py", line 178, in _run_interface
    self._validate_results()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/mni.py", line 400, in _validate_results
    "mask overlaps with the reference image mask." % overlap_perc
AssertionError: Normalization failed: only 32% of the normalized moving image mask overlaps with the reference image mask.

And here is the error showed on the terminal:

2018-09-15 00:42:20,900 nipype.workflow:INFO [Node] Setting-up "workflow_enumerator.funcMRIQC.ReportsWorkflow.GenerateReport" in "/tmp/work/workflow_enumerator/funcMRIQC/ReportsWorkflow/_in_file_..data..sub-001..ses-1..func..sub-001_ses-1_task-Perception_run-01_bold.nii/GenerateReport".
180915-00:42:20,997 nipype.workflow INFO:
	 [Node] Running "GenerateReport" ("nipype.interfaces.utility.wrappers.Function")
2018-09-15 00:42:20,997 nipype.workflow:INFO [Node] Running "GenerateReport" ("nipype.interfaces.utility.wrappers.Function")
2018-09-15 00:42:21,117 mriqc.report:WARNING Building bold report: no exclude index was found
180915-00:42:21,952 nipype.workflow INFO:
	 [Node] Finished "workflow_enumerator.funcMRIQC.ReportsWorkflow.GenerateReport".
2018-09-15 00:42:21,952 nipype.workflow:INFO [Node] Finished "workflow_enumerator.funcMRIQC.ReportsWorkflow.GenerateReport".
180915-00:42:24,812 nipype.workflow ERROR:
	 could not run node: workflow_enumerator.anatMRIQCT1w.SpatialNormalization.SpatialNormalization.a0
2018-09-15 00:42:24,812 nipype.workflow:ERROR could not run node: workflow_enumerator.anatMRIQCT1w.SpatialNormalization.SpatialNormalization.a0
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.14.2', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 250, in main
    mriqc_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

**Comment by Irisfee** [comment]
Finally I realized that I should post the question at google group for help... sorry about posting it at the wrong place. I have figured out the problem, which is caused by the cropped T1w.
