### ISSUE TITLE
BUG in MELODIC interface - ``FileNotFoundError: [Errno 2] No such file or directory ...ICA/melodic_mix``

### ISSUE THREAD

**Issue by pvelasco** [poldracklab/mriqc#779]
Hi devs,

I have a subject for whom Melodic fails to converge in two functional runs.  Instead of generating a report without the ICAs but with everything else, no report is generated for those runs.

Details:

My call:
```
docker run --user $UID:$(id -g) \
     --rm \
     --volume /CBI/UserData:/data \
     poldracklab/mriqc:latest \
         /data/hartleylab/memFreqMRI112 \
         /data/test_katenuss_mriqc/mriqc_reports \
         participant \
         --participant_label 112 \
         --verbose-reports \
         --ica \
         --fft-spikes-detector \
         -w /data/test_katenuss_mriqc/wdir
```

The error in the output:

```
2019-03-07 19:41:36,236 nipype.workflow:INFO [Node] Setting-up "workflow_enumerator.funcMRIQC.ReportsWorkflow.GenerateReport" in "/data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/ReportsWorkflow/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freqreports1_acq-normal_run-01_echo-3_bold.nii.gz/GenerateReport".
190307-19:41:36,718 nipype.workflow INFO:
         [Node] Running "GenerateReport" ("nipype.interfaces.utility.wrappers.Function")
2019-03-07 19:41:36,718 nipype.workflow:INFO [Node] Running "GenerateReport" ("nipype.interfaces.utility.wrappers.Function")
2019-03-07 19:41:36,723 mriqc.report:WARNING Building bold report: no exclude index was found
190307-19:41:37,155 nipype.workflow INFO:
         [Node] Finished "workflow_enumerator.funcMRIQC.ReportsWorkflow.GenerateReport".
2019-03-07 19:41:37,155 nipype.workflow:INFO [Node] Finished "workflow_enumerator.funcMRIQC.ReportsWorkflow.GenerateReport".
2019-03-07 19:56:18,801 niworkflows:INFO Generating report for MELODIC
190307-19:56:18,909 nipype.workflow WARNING:
         [Node] Error on "workflow_enumerator.funcMRIQC.ICA" (/data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/ICA)
2019-03-07 19:56:18,909 nipype.workflow:WARNING [Node] Error on "workflow_enumerator.funcMRIQC.ICA" (/data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/ICA)
190307-19:56:18,991 nipype.workflow ERROR:
         Node ICA.a02 failed to run on host aed81fc22675.
2019-03-07 19:56:18,991 nipype.workflow:ERROR Node ICA.a02 failed to run on host aed81fc22675.
190307-19:56:18,992 nipype.workflow ERROR:
         Saving crash info to /data/test_katenuss_mriqc/mriqc_reports/logs/crash-20190307-195618-UID4265-ICA.a02-7fed2bdf-6c98-4059-99e7-d7c05ee9554e.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 523, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 131, in _post_run_hook
    return super(MELODICRPT, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/mixins/reporting.py", line 47, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 120, in _generate_report
    report_mask=self.inputs.report_mask)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 527, in plot_melodic_components
    timeseries = np.loadtxt(os.path.join(melodic_dir, "melodic_mix"))
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 860, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/ICA/melodic_mix'

2019-03-07 19:56:18,992 nipype.workflow:ERROR Saving crash info to /data/test_katenuss_mriqc/mriqc_reports/logs/crash-20190307-195618-UID4265-ICA.a02-7fed2bdf-6c98-4059-99e7-d7c05ee9554e.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 523, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 131, in _post_run_hook
    return super(MELODICRPT, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/mixins/reporting.py", line 47, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 120, in _generate_report
    report_mask=self.inputs.report_mask)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 527, in plot_melodic_components
    timeseries = np.loadtxt(os.path.join(melodic_dir, "melodic_mix"))
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 860, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/ICA/melodic_mix'

190307-19:56:20,982 nipype.workflow ERROR:
         could not run node: workflow_enumerator.funcMRIQC.ICA.a02
2019-03-07 19:56:20,982 nipype.workflow:ERROR could not run node: workflow_enumerator.funcMRIQC.ICA.a02
```

The crash info in the `logs` folder is:

```
Node: workflow_enumerator.funcMRIQC.ICA
Working directory: /data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/ICA

Node inputs:

ICs = <undefined>
approach = <undefined>
args = <undefined>
bg_image = <undefined>
bg_threshold = <undefined>
compress_report = auto
cov_weight = <undefined>
dim = <undefined>
dim_est = <undefined>
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
epsilon = <undefined>
epsilonS = <undefined>
in_files = ['/data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/sanitize/sub-112_task-freq1_acq-normal_run-01_echo-3_bold_valid.nii.gz']
log_power = <undefined>
mask = <undefined>
max_restart = <undefined>
maxit = <undefined>
migp = <undefined>
migpN = <undefined>
migp_factor = <undefined>
migp_shuffle = <undefined>
mix = <undefined>
mm_thresh = <undefined>
no_bet = True
no_mask = True
no_mm = True
non_linearity = <undefined>
num_ICs = <undefined>
out_all = <undefined>
out_dir = <undefined>
out_mean = <undefined>
out_orig = <undefined>
out_pca = <undefined>
out_report = melodic_reportlet.svg
out_stats = <undefined>
out_unmix = <undefined>
out_white = <undefined>
output_type = NIFTI_GZ
pbsc = <undefined>
rem_cmp = <undefined>
remove_deriv = <undefined>
report = <undefined>
report_maps = <undefined>
report_mask = /data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/fMRIBrainMask/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/erode/sub-112_task-freq1_acq-normal_run-01_echo-3_bold_valid_volreg_tstat_brain_mask_ero.nii.gz
s_con = <undefined>
s_des = <undefined>
sep_vn = <undefined>
sep_whiten = <undefined>
smode = <undefined>
t_con = <undefined>
t_des = <undefined>
tr_sec = <undefined>
update_mask = <undefined>
var_norm = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 523, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 131, in _post_run_hook
    return super(MELODICRPT, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/mixins/reporting.py", line 47, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 120, in _generate_report
    report_mask=self.inputs.report_mask)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 527, in plot_melodic_components
    timeseries = np.loadtxt(os.path.join(melodic_dir, "melodic_mix"))
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 860, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/ICA/melodic_mix'
```

And the ICA/log.txt file in the corresponding workflow folder (skipping many steps):
```

Melodic Version 3.14

melodic -i /data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/sanitize/sub-112_task-freq1_acq-normal_run-01_echo-3_bold_valid.nii.gz --nobet --nomask --no_mm --debug -o /data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/ICA 
---------------------------------------------

Melodic results will be in /data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/ICA

Reading data file /data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/sanitize/sub-112_task-freq1_acq-normal_run-01_echo-3_bold_valid  ...  done
  Estimating data smoothness ...  done 
  Removing mean image ... done
  Normalising by voxel-wise variance ... done
Excluding voxels with constant value ... done

  Data size : 224 x 200464

Starting PCA  ... done
Start whitening using  25 dimensions ... 
  retaining 39.9676 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.962802
  Step no. 2 change : 0.729422
  Step no. 3 change : 0.27576
  Step no. 4 change : 0.114683
  Step no. 5 change : 0.0484415
  Step no. 6 change : 0.0498704
  Step no. 7 change : 0.0498841
  Step no. 8 change : 0.0526857
  Step no. 9 change : 0.0608974
  Step no. 10 change : 0.067419
[...]
  Step no. 497 change : 0.104094
  Step no. 498 change : 0.124789
  Step no. 499 change : 0.151084
Starting PCA  ... done
Start whitening using  23 dimensions ... 
  retaining 39.2714 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.999882
  Step no. 2 change : 0.7987
  Step no. 3 change : 0.798712
[...]
  Step no. 498 change : 0.939589
  Step no. 499 change : 0.777037
Starting PCA  ... done
Start whitening using  21 dimensions ... 
  retaining 38.5663 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.985024
  Step no. 2 change : 0.384216
  Step no. 3 change : 0.194562
[...]
  Step no. 498 change : 0.961083
  Step no. 499 change : 0.911991
Starting PCA  ... done
Start whitening using  19 dimensions ... 
  retaining 37.8502 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.999066
  Step no. 2 change : 0.988311
  Step no. 3 change : 0.396001
[...]
  Step no. 498 change : 0.0166414
  Step no. 499 change : 0.00920357
Starting PCA  ... done
Start whitening using  18 dimensions ... 
  retaining 37.483 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.970398
  Step no. 2 change : 0.871046
  Step no. 3 change : 0.955266
[...]
  Step no. 498 change : 0.3258
  Step no. 499 change : 0.436337
Starting PCA  ... done
Start whitening using  17 dimensions ... 
  retaining 37.1045 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.863366
  Step no. 2 change : 0.939701
  Step no. 3 change : 0.48656
[...]
  Step no. 498 change : 0.947806
  Step no. 499 change : 0.971957
Starting PCA  ... done
Start whitening using  16 dimensions ... 
  retaining 36.7167 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.975561
  Step no. 2 change : 0.637296
  Step no. 3 change : 0.542413
[...]
  Step no. 498 change : 0.859381
  Step no. 499 change : 0.775125
Starting PCA  ... done
Start whitening using  15 dimensions ... 
  retaining 36.3162 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.993056
  Step no. 2 change : 0.83387
  Step no. 3 change : 0.885794
[...]
  Step no. 498 change : 0.821297
  Step no. 499 change : 0.997873
Starting PCA  ... done
Start whitening using  14 dimensions ... 
  retaining 35.9041 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.996373
  Step no. 2 change : 0.947887
  Step no. 3 change : 0.900336
[...]
  Step no. 498 change : 0.404868
  Step no. 499 change : 0.773348
Starting PCA  ... done
Start whitening using  13 dimensions ... 
  retaining 35.4769 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.894602
  Step no. 2 change : 0.652639
  Step no. 3 change : 0.490991
[...]
  Step no. 498 change : 0.0896866
  Step no. 499 change : 0.0561825
Starting PCA  ... done
Start whitening using  12 dimensions ... 
  retaining 35.0306 percent of the variability 
 ... done

Starting ICA estimation using symm

  Step no. 1 change : 0.998418
  Step no. 2 change : 0.794679
  Step no. 3 change : 0.890704
[...]
  Step no. 498 change : 0.693598
  Step no. 499 change : 0.160709

No convergence -- giving up 
```

BTW, this is the third echo of a multi-echo EPI, and Melodic runs successfully on the first two echoes.  It is also successful on all echoes of the other runs.

**Comment by oesteban** [comment]
This will require fixing the interface in Nipype proper, then update the reports to handle such a situation.

Thanks for reporting! And feel invited to take a look into Nipype if you could contribute with a patch :)

**Comment by effigies** [comment]
@pvelasco Are you able to share a dataset that reliably produces this issue?

**Comment by pvelasco** [comment]
@effigies You can download the dataset here:
https://drive.google.com/drive/folders/1R5R1CD8uGiNKF4UnbLQiAjUB_FyG-zES?usp=sharing
Thanks.

**Comment by oesteban** [comment]
I'm currently downloading @pvelasco's data to check the bugfix.
