### ISSUE TITLE
Add support for multisession BIDS datasets

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#8]

**Comment by wtriplett** [comment]
gave this a try (See branch enh/bidsMultiSessionSupport) since ds201 has multiple sessions and will need mriqc in the near future. The anatomical workflow seems OK. The functional workflow seems to crash when making the plots for subjects with only one session. The functional CSV looks good (see below after sorting). 

```
File: crash-20160222-091730-wtriplet-report.pklz
Node: fMRIQC.report
Working directory: /scratch/03872/wtriplet/ds201_mriqcp/BIDS.wrk/fMRIQC/report

Node inputs:

ignore_exception = False
in_csv = /scratch/03872/wtriplet/ds201_mriqcp/BIDS.out/fMRIQC.csv
qctype = functional
settings = {'nthreads': 20, 'write_graph': False, 'skip': [], 'work_dir': '/scratch/03872/wtriplet/ds201_mriqcp/BIDS.wrk', 'bids_root': '/corral-repl/utexas/poldracklab/openfmri/inprocess/ds201_gustav_nilsonne/BIDS', 'output_dir': '/scratch/03872/wtriplet/ds201_mriqcp/BIDS.out'}
sub_list = [ ... lots of them ... ]

Traceback: 
Traceback (most recent call last):
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/plugins/multiproc.py", line 19, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/engine/nodes.py", line 392, in run
    self._run_interface()
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/engine/nodes.py", line 502, in _run_interface
    self._result = self._run_command(execute)
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/engine/nodes.py", line 628, in _run_command
    result = self._interface.run()
  File "/home1/03872/wtriplet/software/nipype/nipype/interfaces/base.py", line 1045, in run
    runtime = self._run_wrapper(runtime)
  File "/home1/03872/wtriplet/software/nipype/nipype/interfaces/base.py", line 995, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home1/03872/wtriplet/software/mriqc/mriqc/interfaces/viz.py", line 163, in _run_interface
    self.inputs.sub_list, settings)
  File "/home1/03872/wtriplet/software/mriqc/mriqc/reports/generators.py", line 137, in workflow_report
    func(df, subject=subid, out_file=qc_ms)
  File "/home1/03872/wtriplet/software/mriqc/mriqc/reports/generators.py", line 392, in report_functional
    out_file=op.join(wd, 'fspatial.pdf'))
  File "/home1/03872/wtriplet/software/mriqc/mriqc/reports/generators.py", line 284, in _write_report
    title='QC measures ' + subtitle)
  File "/home1/03872/wtriplet/software/mriqc/mriqc/interfaces/viz_utils.py", line 133, in plot_all
    zorder=10)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1424, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 386, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 364, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 223, in _xy_from_xy
    raise ValueError("x and y must have same first dimension")
ValueError: x and y must have same first dimension
Interface Report failed to run. 

```

I'll add more details to this comment later this evening (need to switch gears). It did take a few tries to optimize the number of threads for the available ls5 node memory. Each iteration I restarted the workflow mid-stream rather than delete the outputs and re-run from scratch, so maybe something got corrupted. I submitted a job running it on a subset of subjects (including one with a single session) so that might help clear things up.

Hope this information is useful!

||subject|session|scan|bg_mean|
|---|----------|----------|-----|------|
1232|sub-9001|ses-1|task-arrows|111.300354272
53|sub-9001|ses-1|task-arrows|111.300354272
133|sub-9001|ses-1|task-faces|107.345929006
1685|sub-9001|ses-1|task-faces|107.345929006
1144|sub-9001|ses-1|task-hands|109.383956862
24|sub-9001|ses-1|task-hands|109.383956862
1608|sub-9001|ses-1|task-rest_run-1|91.6668615762
528|sub-9001|ses-1|task-rest_run-1|91.6668615762
1024|sub-9001|ses-1|task-rest_run-2|96.9197153538
205|sub-9001|ses-1|task-rest_run-2|96.9197153538
1536|sub-9001|ses-2|task-arrows|98.9900415703
250|sub-9001|ses-2|task-arrows|98.9900415703
115|sub-9001|ses-2|task-faces|97.383043056
1676|sub-9001|ses-2|task-faces|97.383043056
1360|sub-9001|ses-2|task-hands|97.626522697
248|sub-9001|ses-2|task-hands|97.626522697
1661|sub-9001|ses-2|task-rest_run-1|80.796818365
847|sub-9001|ses-2|task-rest_run-1|80.796818365
1532|sub-9001|ses-2|task-rest_run-2|84.2454502238
623|sub-9001|ses-2|task-rest_run-2|84.2454502238
1376|sub-9002|ses-1|task-arrows|160.001317104
765|sub-9002|ses-1|task-arrows|160.001317104
1365|sub-9002|ses-1|task-faces|156.990629829
547|sub-9002|ses-1|task-faces|156.990629829
1373|sub-9002|ses-1|task-hands|156.230993939
552|sub-9002|ses-1|task-hands|156.230993939
1515|sub-9002|ses-1|task-rest_run-1|93.5018311698
292|sub-9002|ses-1|task-rest_run-1|93.5018311698
1073|sub-9002|ses-1|task-rest_run-2|95.7726420411

**Comment by oesteban** [comment]
Hey @wtriplett, could you give me the path of this ds201 so that I can check if my current implementation works? Thanks!

**Comment by oesteban** [comment]
Checking right now on ds201. Apparently works well, with the code of @wtriplett and the additions for the new single-subject execution mode. I'll reopen only if it fails for this reason.
