### ISSUE TITLE
Issues with mriqc installation using singularity

### ISSUE THREAD

**Issue by estephanmoana** [poldracklab/mriqc#827]
Hello, I am trying to run mriqc as a singularity container and I am experiencing issues. I googled around for ways to do it, as I could not find in the documentation the steps needed <https://mriqc.readthedocs.io/en/latest/install.html>. I successfully installed a SIF image file with the latest mriqc (mriqc v0.15.2rc1) - as a side note, it took 2h40m using a HCP node with 128 cores and 250GB of memory.

The main issue when trying mriqc in a single subject is this error: "OSError: [Errno 28] No space left on device". Full output is below:
cn1127:~ moana004$ mriqc_current=${HOME}/mriqc/mriqc_v0.15.2rc1.sif; mriqc_outputdir=${HOME}/project_K99_ChrTMDHCP/QA_mri_data/mriqc_output; BIDSoutput_dir=${HOME}/project_K99_ChrTMDHCP/BIDS_output; mriqc_workdir=${HOME}/temp/mriqc_workdir; subj_list="10001"; NSLOTS=`cat $PBS_NODEFILE | wc -l`; memavail_GB=`awk '/MemFree/ { printf "%.0f \n", $2/1024/1024 }' /proc/meminfo`
cn1127:~ moana004$
cn1127:~ moana004$
cn1127:~ moana004$ start=`date`; singularity run --cleanenv --containall --bind ${mriqc_current},${BIDSoutput_dir},${mriqc_outputdir},${mriqc_workdir} ${mriqc_current} ${BIDSoutput_dir}/ ${mriqc_outputdir}/ participant --participant-label ${subj_list} --modalities T1w --work-dir ${mriqc_workdir} --nprocs ${NSLOTS} --mem_gb ${memavail_GB}; end=`date`; echo; echo -e "Start: ${start}\nEnd: ${end}"
2020-01-18 17:51:22,292 mriqc:IMPORTANT
    Running MRIQC version 0.15.2rc1:
      * BIDS dataset path: /home/moanae/moana004/project_K99_ChrTMDHCP/BIDS_output.
      * Output folder: /home/moanae/moana004/project_K99_ChrTMDHCP/QA_mri_data/mriqc_output.
      * Analysis levels: participant.
   
200118-17:53:58,596 nipype.workflow INFO:
     Building anatomical MRIQC workflow, datasets list: ['sub-10001/ses-01/anat/sub-10001_ses-01_acq-T1wMPR_run-01_T1w.nii.gz', 'sub-10001/ses-01/anat/sub-10001_ses-01_acq-T1wMPR_run-02_T1w.nii.gz']
2020-01-18 17:53:58,596 nipype.workflow:INFO Building anatomical MRIQC workflow, datasets list: ['sub-10001/ses-01/anat/sub-10001_ses-01_acq-T1wMPR_run-01_T1w.nii.gz', 'sub-10001/ses-01/anat/sub-10001_ses-01_acq-T1wMPR_run-02_T1w.nii.gz']
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask.nii.gz
29.0B [00:00, 1.04kB/s]                                                        
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_desc-head_mask.nii.gz
953B [00:00, 6.44kB/s]                                                          
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_label-CSF_probseg.nii.gz
5.37kB [00:00, 16.9kB/s]                                                        
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_label-GM_probseg.nii.gz
7.39kB [00:00, 21.2kB/s]                                                        
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_label-WM_probseg.nii.gz
  4%|█▍                                      | 238/6.75k [00:00<00:02, 2.18kB/s]
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 144, in _s3_get
    f.write(data)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/bin/mriqc_run.py", line 418, in init_mriqc
    wf_list.append(build_workflow(dataset[mod], mod, settings=settings))
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/workflows/core.py", line 27, in build_workflow
    workflow = anat_qc_workflow(dataset, mod=mod, settings=settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/workflows/anatomical.py", line 94, in anat_qc_workflow
    iqmswf = compute_iqms(settings, modality=mod)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/workflows/anatomical.py", line 256, in compute_iqms
    label=['CSF', 'GM', 'WM'])]
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 39, in get
    _s3_get(filepath)
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 144, in _s3_get
    f.write(data)
OSError: [Errno 28] No space left on device

I tried to use a "sandbox" version of mriqc (by using "singularity build --sandbox" on the mriqc SIF image file), but it cannot run:

cn1127:~ moana004$ date; singularity run --cleanenv --containall ${HOME}/mriqc_sandbox/mriqc_v0.15.2rc1 --version --version
Sat Jan 18 11:49:42 CST 2020
FATAL:   container creation failed: mount overlay->/var/singularity/mnt/session/final error: can't mount overlay filesystem to /var/singularity/mnt/session/final: invalid argument

These are the steps used to install mriqc:
### Loading necessary UMN MSI modules
module load singularity/current

### Setting up singularity variables
# Variables
SINGULARITY_LOCALCACHEDIR=${HOME}/temp/singularity_tempdir
SINGULARITY_CACHEDIR=${HOME}/temp/singularity_tempdir
SINGULARITY_TMPDIR=${HOME}/temp/singularity_tempdir
# Exporting variables
export SINGULARITY_LOCALCACHEDIR SINGULARITY_CACHEDIR SINGULARITY_TMPDIR
# Creating folders
mkdir -p ${SINGULARITY_LOCALCACHEDIR}
# Variable for mriqc container
mriqc_dir=mriqc

## Commands in a single line
SINGULARITY_LOCALCACHEDIR=${HOME}/temp/singularity_tempdir; SINGULARITY_CACHEDIR=${HOME}/temp/singularity_tempdir; SINGULARITY_TMPDIR=${HOME}/temp/singularity_tempdir; export SINGULARITY_LOCALCACHEDIR SINGULARITY_CACHEDIR SINGULARITY_TMPDIR; mkdir -p ${SINGULARITY_LOCALCACHEDIR}; mriqc_dir=mriqc

### Create folder for fMRI prep within ${HOME} folder
mkdir ${HOME}/${mriqc_dir}

## Adapted from this source: <https://neurostars.org/t/preferred-way-to-create-mriqc-singularity-container/948>
# date; cd ${HOME}/${mriqc_dir}; singularity pull docker://poldracklab/mriqc:latest; cd ${HOME}; date
start=`date`; date; singularity build ${HOME}/${mriqc_dir}/mriqc_latest.sif docker://poldracklab/mriqc:latest; end=`date`; echo; echo -e "Start: ${start}\nEnd: ${end}"

## Processing time:
# Start: Sat Jan 18 08:00:12 CST 2020
# End: Sat Jan 18 10:40:49 CST 2020

### Checking mriqc version installed
date; singularity run --cleanenv --containall ${HOME}/${mriqc_dir}/mriqc_latest.sif --version

## Output
# Sat Jan 18 10:44:53 CST 2020
# mriqc v0.15.2rc1

### Renaming the mriqc image to have the version in the image file name
# Variable with version
mriqc_version=`singularity run --cleanenv --containall ${HOME}/${mriqc_dir}/mriqc_latest.sif --version | awk '{print $2}'`
# Renaming proper
mv ${HOME}/${mriqc_dir}/mriqc_latest.sif ${HOME}/${mriqc_dir}/mriqc_${mriqc_version}.sif

## Creating another mriqc folder
mkdir ${HOME}/${mriqc_dir}_sandbox

# Command
start=`date`; date; singularity build --sandbox ${HOME}/${mriqc_dir}_sandbox/mriqc_${mriqc_version} ${HOME}/${mriqc_dir}/mriqc_${mriqc_version}.sif; end=`date`; echo; echo -e "Start: ${start}\nEnd: ${end}"

## Processing time:
# Start: Sat Jan 18 11:20:52 CST 2020
# End: Sat Jan 18 11:34:42 CST 2020

### Checking mriqc version installed (sanity check to see if mriqc is working)
date; singularity run --cleanenv --containall ${HOME}/mriqc_sandbox/mriqc_v0.15.2rc1 --version

## output
# cn1127:~ moana004$ date; singularity run --cleanenv --containall ${HOME}/mriqc_sandbox/mriqc_v0.15.2rc1 --version --version
# Sat Jan 18 11:49:42 CST 2020
# FATAL:   container creation failed: mount overlay->/var/singularity/mnt/session/final error: can't mount overlay filesystem to /var/singularity/mnt/session/final: invalid argument

Any advice on how to get a singularity container for mriqc running? Thank you.

Estephan

**Comment by oesteban** [comment]
This looks like a problem in the interaction of TemplateFlow and Singularity. Although this issue is old (apologies for the slow response), it would be worth to know whether this is still an issue.

More information about how to go around these problems is given at https://www.nipreps.org/apps/singularity/#templateflow-and-singularity

Please reopen if necessary.
