### ISSUE TITLE
Group-level command shown in tutorial runs into error

### ISSUE THREAD

**Issue by tashrifbillah** [poldracklab/mriqc#832]
Both the below commands run into errror:
`
mriqc ~/INTRuST_BIDS_tb571/ ~/mriqc-out/ group
`

`
mriqc ~/INTRuST_BIDS_tb571/ ~/mriqc-out/ group --participant-label 003GNX007 003GNX012 003GNX021
`

Error:

```bash
2020-03-10 09:49:41,149 mriqc:IMPORTANT
    Running MRIQC version 0.15.2rc1+36.gf6c7066:
      * BIDS dataset path: ~/INTRuST_BIDS_tb571.
      * Output folder: /home/ek520/mriqc-out.
      * Analysis levels: group.

Traceback (most recent call last):
  File "/rfanfs/pnl-zorro/software/pnlpipe3/miniconda3/envs/pnlpipe3/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.15.2rc1+36.gf6c7066', 'console_scripts', 'mriqc')()
  File "/rfanfs/pnl-zorro/software/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/mriqc-0.15.2rc1+36.gf6c7066-py3.6.egg/mriqc/bin/mriqc_run.py", line 295, in main
Exception: No data found. No group level reports were generated.
```

However, `participant` level analysis runs fine:
```
mriqc ~/INTRuST_BIDS_tb571/ ~/mriqc-out/ participant --participant-label 003GNX007 003GNX012 003GNX021
```

So, am I not running group-level analysis right? I am following the commands shown here:
https://mriqc.readthedocs.io/en/stable/running.html#running-mriqc

**Comment by oesteban** [comment]
Maybe MRIQC is not expanding the user (`~/`) from some paths?

**Comment by tashrifbillah** [comment]
> Maybe MRIQC is not expanding the user shortcuts (~/) from some paths?

And it is expanding for participant level?

**Comment by tashrifbillah** [comment]
While trying to find a way around, the following seems to perform group level analysis:

> mriqc ~/INTRuST_BIDS_tb571/ ~/mriqc-out/ participant


```bash
2020-03-24 22:54:56,030 mriqc:IMPORTANT 
    Running MRIQC version 0.15.2rc1+36.gf6c7066:
      * BIDS dataset path: /home/tb571/Downloads/INTRuST_BIDS/rawdata.
      * Output folder: /tmp/mriqc-ica.
      * Analysis levels: group, participant.
    
...
...
```

**Comment by dfsp-spirit** [comment]
I just run into the same issue when setting the analysis level to `group`, using the latest Docker version of `mriqc`, which currently is `0.15.2`:

    docker run -it --rm -v /home/myuser/data/mydataset_BIDS:/data:ro -v /home/myuser/mriqc_aims:/out poldracklab/mriqc:latest /data /out group
    Traceback (most recent call last):
     File "/usr/local/miniconda/bin/mriqc", line 10, in <module> sys.exit(main())
     File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 113, in main
    raise Exception("No data found. No group level reports were generated.")
    Exception: No data found. No group level reports were generated.

However, the workaround mentioned by @tashrifbillah does not seem to work for me, the analysis is set to `participant` only (as I would expect from the command line, btw):

    docker run -it --rm -v /home/timschaefer/data/:/data:ro -v /home/timschaefer/mriqc_aims:/out poldracklab/mriqc:latest /data /out participant --no-sub
    200722-09:46:03,314 cli IMPORTANT:
    Running MRIQC version 0.15.2:
      * BIDS dataset path: /data.
      * Output folder: /out.
      * Analysis levels: ['participant'].

My input is a BIDS folder of structural T1w scans (checked with the [online BIDS Validator](https://bids-standard.github.io/bids-validator/)). I doubt it matters, but I am running Docker version 19.03.12 under Ubuntu Linux 20.04.

Any updates on this, or ideas what I may be doing wrong?

**Comment by tashrifbillah** [comment]
> However, the workaround mentioned by @tashrifbillah does not seem to work for me, the analysis runs, but is set to participant only (as I would expect from the command line, btw):

@dfsp-spirit , do you have more  than one case in `/data`?

**Comment by tashrifbillah** [comment]
Again, for what it's worth, my command runs on a bare-metal installation, not through docker container.

**Comment by dfsp-spirit** [comment]
Yes, I have > 700 cases in there. Could it be that I need to run the participant-level analysis first, and only then the group level analysis is gonna work? I am currently trying that, but it is still running since yesterday morning, so I can't tell yet.

I know that you are running bare metal, and I also noticed that we are using slightly different versions, which may also explain why it does not work for me.

**Comment by PibeChorro** [comment]
Hey, having the same problem here. I wanted to run MRIQC on my realigned functional data to see if it could "save" a critical subject that moved a lot. 
My realigned data set has the same structure as my raw data only missing some meta files (.json, tsv, README) so it worked on participant level.
I thought it might be, because I have only functional data, so I played around with the ```-m``` flag. Setting it to ```"func``` instead of ```bold``` gave me the following
`*participant_label: ['01', '02' ... '24']
*session: None
*run: None
*task: None
bids_type: ['func']`
However I have 12 runs and one task (no session indeed). 
Maybe this helps
