### ISSUE TITLE
singularity under docker on OSX: forkserver.py -- Invalid argument

### ISSUE THREAD

**Issue by yarikoptic** [poldracklab/mriqc#886]
First observed by @effigies upon my request to try out my fixes to https://github.com/ReproNim/containers/ .

Seems to be OSX specific since works fine on Linux (sandwidching through docker needs to be forced by setting `REPRONIM_USE_DOCKER=1`

```shell
containers % REPRONIM_DOCKER_OPTS=-it bash -x containers/scripts/singularity_cmd exec containers/images/bids/bids-mriqc--0.16.0.sing bash
...
Singularity> cd /var/folders/tk/5_lnk94x727gwq_x4z6mf1x00000gp/T/repro-SkBMLev/ds000003-qc
...
Singularity> python -m pdb -m mriqc.cli.run sourcedata . participant
> /usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py(2)<module>()
-> """MRIQC run script."""
(Pdb) c
210116-16:53:49,238 cli IMPORTANT:
         
    Running MRIQC version 0.16.0:
      * BIDS dataset path: /var/folders/tk/5_lnk94x727gwq_x4z6mf1x00000gp/T/repro-SkBMLev/ds000003-qc/sourcedata.
      * Output folder: /var/folders/tk/5_lnk94x727gwq_x4z6mf1x00000gp/T/repro-SkBMLev/ds000003-qc.
      * Analysis levels: ['participant'].

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/pdb.py", line 1695, in main
    pdb._runmodule(mainpyfile)
  File "/usr/local/miniconda/lib/python3.7/pdb.py", line 1540, in _runmodule
    self.run(code)
  File "/usr/local/miniconda/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 2, in <module>
    """MRIQC run script."""
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 37, in main
    with Manager() as mgr:
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/context.py", line 56, in Manager
    m.start()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/managers.py", line 543, in start
    self._process.start()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/popen_forkserver.py", line 51, in _launch
    self.sentinel, w = forkserver.connect_to_new_process(self._fds)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/forkserver.py", line 64, in connect_to_new_process
    self.ensure_running()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/forkserver.py", line 118, in ensure_running
    listener.bind(address)
OSError: [Errno 22] Invalid argument
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/local/miniconda/lib/python3.7/multiprocessing/forkserver.py(118)ensure_running()
-> listener.bind(address)
```
and that address is some (temporary) file (socket?)

```
(Pdb) p address
'/tmp/pymp-oexpbmbp/listener-u1gszjtw'
(Pdb) 
[1]+  Stopped                 python -m pdb -m mriqc.cli.run sourcedata . participant
Singularity> ls -l /tmp/pymp-oexpbmbp/listener-u1gszjtw
ls: cannot access '/tmp/pymp-oexpbmbp/listener-u1gszjtw': No such file or directory
```

to reproduce -- have docker, datalad and datalad-container installed

<details>
<summary>a minimalistic howto to install datalad/datalad-container from total scratch on OSX including brew and miniconda</summary> 

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  # homebrew
curl -fsSL http://get.datalad.org > /tmp/datalad-install.py
python3 /tmp/datalad-install.py git-annex -m brew miniconda --path ~/miniconda3 --batch datalad -m conda
source ~/miniconda3/etc/profile.d/conda.sh; conda activate base
conda install -c conda-forge -y datalad-container
conda uninstall -y datalad-container  # no clue why needed: https://github.com/conda-forge/datalad-container-feedstock/issues/7
conda install -c conda-forge -t datalad-container
```

</details>

and then just run
```
bash <(sed -n -e '/^ *#!/,/^```$/p' README.md | grep -v '```')
```
in the local clone of https://github.com/ReproNim/containers/ and you should arrive at that 

```
OSError: [Errno 22] Invalid argument
```
if on OSX

**Comment by chaselgrove** [comment]
This isn't an mriqc issue (see https://github.com/ReproNim/containers/issues/57) and can be closed here.

**Comment by yarikoptic** [comment]
if I got it right -- with all the wonderfully long temporary paths like `/var/folders/tk/5_lnk94x727gwq_x4z6mf1x00000gp/T/repro-SkBMLev` on OSX, OSX runs out of juice (path length) if such a path is exposed somewhere deep within docker/singularity sandwich leading to this obscure error...  Thank you @chaselgrove for tracking it down
