### ISSUE TITLE
Error while decode JSON from anat_preproc_wf/fs_isrunning

### ISSUE THREAD

**Issue by mamuerie** [poldracklab/mriqc#907]
Dear mriqc-team, 
unfortunately, I am not able to run mriqc on the participant level on any participant.
I used the following code (on windows): 

`docker run -it --rm -v "c:\Users\Marie\Documents\IPU\Experiment\fMRIPrep\datasets\MOMAP":/data:ro -v "c:\Users\Marie\Documents\IPU\Experiment\fMRIPrep\datasets\MOMAP\derivatives\mriqc\sub-105":/out poldracklab/mriqc:0.16.1 /data /out participant --participant_label 105`

and got the following error message:

> Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 280, in _index_metadata
    payload = json.load(handle)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
 File "/usr/local/miniconda/bin/mriqc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 16, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/parser.py", line 374, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/config.py", line 519, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/config.py", line 185, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/config.py", line 400, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 155, in __init__
    indexer(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 111, in __call__
    self._index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 284, in _index_metadata
    raise IOError(msg) from e
OSError: Error occurred while trying to decode JSON from file '/data/temp/fmriprep_wf/single_subject_105_wf/anat_preproc_wf/fs_isrunning/_0xdf246788ee344b6009847bd0cc4832c8.json'.

The file referred by the error looks like this: 

> [('function_str', 'def fs_isRunning(subjects_dir, subject_id, mtime_tol=86400, logger=None):\n    """\n    Checks FreeSurfer subjects dir for presence of recon-all blocking ``IsRunning`` files,\n    and optionally removes any based on the modification time.\n\n    Parameters\n    ----------\n    subjects_dir : os.PathLike or None\n        Existing FreeSurfer subjects directory\n    subject_id : str\n        Subject label\n    mtime_tol : int\n        Tolerance time (in seconds) between current time and last modification of ``recon-all.log``\n\n    Returns\n    -------\n    subjects_dir : os.PathLike or None\n\n    """\n    from pathlib import Path\n    import time\n\n    if subjects_dir is None:\n        return subjects_dir\n    subj_dir = Path(subjects_dir) / subject_id\n    if not subj_dir.exists():\n        return subjects_dir\n\n    isrunning = tuple(subj_dir.glob("scripts/IsRunning*"))\n    if not isrunning:\n        return subjects_dir\n    reconlog = subj_dir / "scripts" / "recon-all.log"\n    # if recon log doesn\'t exist, just clear IsRunning\n    mtime = reconlog.stat().st_mtime if reconlog.exists() else 0\n    if (time.time() - mtime) < mtime_tol:\n        raise RuntimeError(f"""\\\nThe FreeSurfer\'s subject folder <{subj_dir}> contains IsRunning files that \\\nmay pertain to a current or past execution: {isrunning}.\nFreeSurfer cannot run if these are present, to avoid interfering with a running \\\nprocess. Please, make sure no other process is running ``recon-all`` on this subject \\\nand proceed to delete the files listed above.""")\n    for fl in isrunning:\n        fl.unlink()\n    if logger:\n        logger.warn(f\'Removed "IsRunning*" files found under {subj_dir}\')\n    return subjects_dir\n'), ('logger', <Logger nipype.workflow (INFO)>), ('subject_id', 'sub-105'), ('subjects_dir', '/out/freesurfer'), ('needed_outputs', ['out'])]

Any ideas on how to solve the problem and where it comes from?
Thanks for your help!

**Comment by oesteban** [comment]
Hi @mamuerie, sorry I got to read this so incredibly late.

Under `c:\Users\Marie\Documents\IPU\Experiment\fMRIPrep\datasets\MOMAP` you have a `temp` folder with intermediate results from *fMRIPrep* that is being indexed by *PyBIDS* as if it contained input data.

If your subjects' data are directly hanging from `c:\Users\Marie\Documents\IPU\Experiment\fMRIPrep\datasets\MOMAP`, then you should remove any BIDS incompatible folder (such as this `temp` folder). Alternatively, if your data are under a specific and isolated directory, then point mriqc to that folder.

Please reopen if you couldn't fix the issue.
