### ISSUE TITLE
Error when building MRIQC container locally

### ISSUE THREAD

**Issue by lawlessrd** [poldracklab/mriqc#916]
Running on Ubuntu 20.04. When directly pulling the docker image from dockerhub, I get no issues and everythin works correctly. Below are the commands I input and the resulting output for checking the version.

`docker pull poldracklab/mriqc:0.16.1`
`docker run -it poldracklab/mriqc:0.16.1 --version`
> MRIQC v0.16.1

However, when I build locally through the github repo using the following command:

`docker build -t git_test/mriqc:0.16.1 https://github.com/poldracklab/mriqc.git#0.16.1`

It builds successfully, but when trying to run the container I get hit with an error. 
`docker run -it git_test/mriqc:0.16.1 --version`

>  Traceback (most recent call last):
>   File "/usr/local/miniconda/bin/mriqc", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 16, in main
>     parse_args()
>   File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/parser.py", line 371, in parse_args
>     parser = _build_parser()
>   File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/parser.py", line 59, in _build_parser
>     currentv = Version(config.environment.version)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/packaging/version.py", line 298, in __init__
>     raise InvalidVersion("Invalid version: '{0}'".format(version))
> packaging.version.InvalidVersion: Invalid version: ''

**Comment by lawlessrd** [comment]
Resolved. When building the container from github I didn't realize I needed to add 
`docker build --build-arg VERSION=0.16.1`
