### ISSUE TITLE
Which version of scikit-learn should be installed?

### ISSUE THREAD

**Issue by ephong93** [poldracklab/mriqc#923]
1. "requirements.txt" file ( https://raw.githubusercontent.com/poldracklab/mriqc/master/requirements.txt ) does not exist.
2. I got the following error:
```sh
Traceback (most recent call last):
  File "/usr/local/bin/mriqc_clf", line 33, in <module>
    sys.exit(load_entry_point('mriqc==0.16.1+5.g6324774', 'console_scripts', 'mriqc_clf')())
  File "/usr/local/lib/python3.6/dist-packages/mriqc-0.16.1+5.g6324774-py3.6.egg/mriqc/bin/mriqc_clf.py", line 245, in main
  File "/usr/local/lib/python3.6/dist-packages/mriqc-0.16.1+5.g6324774-py3.6.egg/mriqc/classifier/helper.py", line 184, in __init__
  File "/usr/local/lib/python3.6/dist-packages/mriqc-0.16.1+5.g6324774-py3.6.egg/mriqc/classifier/helper.py", line 705, in load
  File "/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.6/pickle.py", line 1338, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python3.6/pickle.py", line 1388, in find_class
    __import__(module, level=0)
  File "/usr/local/lib/python3.6/dist-packages/mriqc-0.16.1+5.g6324774-py3.6.egg/mriqc/classifier/sklearn/__init__.py", line 5, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mriqc-0.16.1+5.g6324774-py3.6.egg/mriqc/classifier/sklearn/cv_nested.py", line 34, in <module>
ImportError: cannot import name 'logger'
```

3. I installed scikit-learn==0.20.4 following #798 . But I now get this error:
```sh
Traceback (most recent call last):
  File "/usr/local/bin/mriqc_clf", line 33, in <module>
    sys.exit(load_entry_point('mriqc==0.16.1+5.g6324774', 'console_scripts', 'mriqc_clf')())
  File "/usr/local/bin/mriqc_clf", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 168, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/mriqc-0.16.1+5.g6324774-py3.6.egg/mriqc/bin/mriqc_clf.py", line 7, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (scikit-learn 0.20.4 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('scikit-learn>=0.21'), {'nilearn'})```

**Comment by ephong93** [comment]
I removed nilearn and reinstalled nilearn==0.3.0 and it seems work
